import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.listings': 'Listings',
    'nav.reviews': 'Reviews',
    'nav.bulkEdits': 'Bulk Edits',
    'nav.editsLog': 'Edits Log',
    'nav.publishing': 'Publishing',
    'nav.reports': 'Reports',
    'nav.seo': 'SEO',
    'nav.localSeo': 'Local SEO',
    'nav.realComment': 'Real Comment',
    'nav.rednoteSeo': 'Rednote SEO',
    'nav.comments': 'Comments',
    'nav.posts': 'Posts',
    'nav.docs': 'Documentation',
    'nav.settings': 'Settings',
    'nav.help': 'Help',
    'nav.connectBusiness': 'Connect Business',
    'nav.signOut': 'Sign Out',
    'nav.profile': 'Profile',
    'nav.changeAvatar': 'Change Avatar',
    'nav.changePassword': 'Change Password',
    'nav.language': 'Language',
    'nav.theme': 'Theme',
    'nav.light': 'Light',
    'nav.dark': 'Dark',
    'nav.salesDoc': 'Feature Docs',

    // Header
    'header.search': 'Search...',
    'header.locations': 'Locations',
    'header.keywords': 'Keywords',

    // Comments Gen
    'comments.title': 'Auto Comments',
    'comments.subtitle': 'Generate and schedule reviews using your managed Google accounts.',
    'comments.quota': 'Monthly Quota',
    'comments.remaining': 'remaining',
    'comments.setup': 'Task Setup',
    'comments.selectAccount': 'Select Account',
    'comments.targetLocation': 'Target Location (Optional)',
    'comments.generation': 'Content Generation',
    'comments.keywords': 'Keywords / Context',
    'comments.keywordsPlaceholder': 'e.g., great coffee, friendly staff, fast wifi',
    'comments.generateBtn': 'Generate',
    'comments.reviewContent': 'Review Content',
    'comments.reviewPlaceholder': 'Generated review will appear here. You can edit it before saving.',
    'comments.photos': 'Photos (Optional)',
    'comments.addPhoto': 'Add Photo',
    'comments.saveTask': 'Save Task to Queue',
    'comments.quotaExceeded': 'Monthly quota exceeded. Cannot save new tasks.',
    'comments.errorKeywords': 'Please enter keywords first.',
    'comments.errorAccount': 'Please select a Google account.',
    'comments.errorContent': 'Please generate or write comment content.',
    'comments.success': 'Comment task saved successfully! It is now pending execution.',

    // App
    'app.title.dashboard': 'PinKernel SEO',
    'app.title.listings': 'PinKernel SEO',
    'app.title.reviews': 'PinKernel SEO',
    'app.title.comments-gen': 'PinKernel SEO',
    'app.title.rank-tracker': 'PinKernel SEO',
    'app.title.posts': 'PinKernel SEO',
    'app.title.reports': 'PinKernel SEO',
    'app.title.keywords': 'PinKernel SEO',
    'app.title.settings': 'PinKernel SEO',
    'app.title.docs': 'PinKernel SEO',
    'app.configWarning': 'Please configure your API settings to use the application.',
    'app.goToSettings': 'Go to Settings',
    'dashboard.subtitle': 'Welcome back. Here\'s what\'s happening with your locations today.',
    'dashboard.totalLocations': 'Total Locations',
    'dashboard.avgRating': 'Avg Rating',
    'dashboard.totalReviews': 'Total Reviews',
    'dashboard.replyRate': 'Reply Rate',
    'dashboard.unreplied': 'Unreplied',
    'dashboard.replied': 'Replied',
    'dashboard.viewAll': 'View All',
    'dashboard.traffic': 'Traffic Trend',
    'dashboard.views': 'Views',
    'dashboard.clicks': 'Clicks',
    'dashboard.topKeywords': 'Top Keywords',
    'dashboard.keyword': 'Keyword',
    'dashboard.rank': 'Rank',
    'dashboard.volume': 'Volume',
    'dashboard.trend': 'Trend',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.activity.review': 'New 5-Star Review',
    'dashboard.activity.post': 'Auto-Post Success',
    'dashboard.activity.sync': 'Location data synced',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.action.reply': 'Reply to Reviews',
    'dashboard.action.post': 'Create Post',
    'dashboard.action.sync': 'Sync Data',
    'dashboard.locationFocus': 'Location Focus',
    'dashboard.heatmap': 'Local Visibility Heatmap',
    'dashboard.updated': 'Updated',
    'dashboard.aiSuggestion': 'AI Suggestion',
    'dashboard.aiSuggestionDesc': 'You have 12 unanswered questions on the Arlington profile. Respond now to boost engagement.',
    'dashboard.openAiAssistant': 'Open AI Assistant',
    'dashboard.health': 'Health',
    'dashboard.profileCompleteness': 'Profile Completeness',
    'dashboard.businessName': 'Business name',
    'dashboard.address': 'Address (Location)',
    'dashboard.website': 'Website URL',
    'dashboard.phoneNumber': 'Phone number',
    'dashboard.numberOfReviews': 'Number of reviews',
    'dashboard.per100': '/ 100',
    'dashboard.per5': '/ 5',
    'dashboard.reviewsUnit': 'reviews',
    'dashboard.performanceOverview': 'Performance overview across all your business locations',
    'dashboard.last7Days': 'Last 7 Days',
    'dashboard.last30Days': 'Last 30 Days',
    'dashboard.last90Days': 'Last 90 Days',
    'dashboard.last12Months': 'Last 12 Months',
    'dashboard.searchViews': 'Search Views',
    'dashboard.mapViews': 'Map Views',
    'dashboard.websiteClicks': 'Website Clicks',
    'dashboard.directionRequests': 'Direction Requests',
    'dashboard.phoneCalls': 'Phone Calls',
    'dashboard.publishedPosts': 'Published Posts',
    'dashboard.overviewImpressions': 'Overview: Impressions',
    'dashboard.impressionsDesc': 'Search views and map views over time',
    'dashboard.overviewActions': 'Overview: Actions',
    'dashboard.actionsDesc': 'Website clicks, directions, and calls over time',
    'dashboard.all': 'All',
    'dashboard.positive': 'Positive',
    'dashboard.negative': 'Negative',
    'dashboard.noReviewsYet': 'No reviews yet',
    'dashboard.reviewTrends': 'Review Trends',
    'dashboard.newReviewsVsResponses': 'New reviews vs responses over time',
    'dashboard.excellent': 'Excellent',
    'dashboard.good': 'Good',
    'dashboard.needsAttention': 'Needs Attention',
    'dashboard.poor': 'Poor',
    'dashboard.averPostingTime': 'Aver. Posting Time',
    'dashboard.averResponseTime': 'Aver. Response Time',
    'dashboard.responsePct': 'Response %',
    'dashboard.loadingData': 'Loading dashboard data...',
    'dashboard.selectPeriod': 'Select period',
    'dashboard.recentReviews': 'Recent Reviews',
    'dashboard.allLocations': 'All Locations',
    'dashboard.noDataAvailable': 'No data available',

    // Listings
    'listings.title': 'Locations & Profiles',
    'listings.subtitle': 'Manage your business information across all locations.',
    'listings.syncAll': 'Sync All',
    'listings.addLocation': 'Add Location',
    'listings.search': 'Search locations...',
    'listings.status.synced': 'Synced',
    'listings.status.pending': 'Pending',
    'listings.table.name': 'Name',
    'listings.table.address': 'Address',
    'listings.table.phone': 'Phone',
    'listings.table.status': 'Status',
    'listings.table.actions': 'Actions',
    'listings.edit': 'Edit',
    'listings.view': 'View',
    'listings.editor': 'Business Info Editor',
    'listings.noLocations': 'No Locations Found',
    'listings.noLocationsDesc': 'Connect your Google Business Profile and sync to view and edit your locations here.',
    'listings.connectGoogle': 'Connect Google Account',
    'listings.businessHours': 'Business Hours',
    'listings.days.monday': 'Monday',
    'listings.days.tuesday': 'Tuesday',
    'listings.days.wednesday': 'Wednesday',
    'listings.days.thursday': 'Thursday',
    'listings.days.friday': 'Friday',
    'listings.days.saturday': 'Saturday',
    'listings.days.sunday': 'Sunday',
    'listings.discard': 'Discard Changes',
    'listings.save': 'Save Profile',
    'listings.mapPresence': 'Map Presence',
    'listings.verifiedPosition': 'Verified Position',
    'listings.searchPerformance': 'Search Performance',
    'listings.directSearches': 'Direct Searches',
    'listings.discoverySearches': 'Discovery Searches',
    'listings.viewAnalytics': 'View Detailed Analytics',

    // Reviews
    'reviews.title': 'Unified Inbox',
    'reviews.subtitle': 'Manage and reply to customer reviews across all locations.',
    'reviews.filter.all': 'All Reviews',
    'reviews.filter.unreplied': 'Unreplied',
    'reviews.filter.replied': 'Replied',
    'reviews.search': 'Search reviews...',
    'reviews.replyBtn': 'Reply',
    'reviews.aiReplyBtn': 'AI Reply',
    'reviews.repliedBy': 'Replied by',
    'reviews.aiGenerated': 'AI Generated',
    'reviews.syncReviews': 'Sync reviews',
    'reviews.filter': 'Filter',
    'reviews.noReviews': 'No reviews found.',
    'reviews.noReviewsDesc': 'Click Sync reviews to import from Google.',
    'reviews.noComment': 'No comment provided.',
    'reviews.googleVerified': 'Google verified',
    'reviews.posted': 'Posted',
    'reviews.replied': 'Replied',
    'reviews.respondToReview': 'Respond to review',
    'reviews.replyPlaceholder': 'Write your reply…',
    'reviews.readyToSend': 'Ready to send',
    'reviews.sendReply': 'Send reply',
    'reviews.selectReview': 'Select a review to read details',
    'reviews.noReviewsAvailable': 'No reviews yet',
    'listings.placesApiKeyBanner': 'Google Places API key required. Add it at the top of Settings → Google Business Profile, or set GOOGLE_PLACES_API_KEY in .env.',
    'listings.placesApiKeyManualError': 'Configure the Google Places API key in Settings (Google Business Profile section at the top), or set GOOGLE_PLACES_API_KEY in .env.',

    // Settings
    'settings.title': 'API Settings',
    'settings.subtitle': 'Configure your API keys to connect your local business data. These keys are stored securely and are required to sync your listings and reviews.',
    'settings.googleApi': 'Google Business Profile API',
    'settings.googleClientId': 'Google Client ID',
    'settings.googleClientSecret': 'Google Client Secret',
    'settings.geminiApi': 'Google Gemini API',
    'settings.geminiApiKey': 'Gemini API Key',
    'settings.googlePlacesApiKey': 'Google Places API Key',
    'settings.googlePlacesSectionTitle': 'Google Places API',
    'settings.googlePlacesApiKeyDesc': 'Used to search and validate Google Business locations on the Listings page. Separate from OAuth (Business Profile sync).',
    'settings.googlePlacesApiKeyHint': 'Enable Places API in Google Cloud Console, then create an API key (restrict it to Places for production).',
    'settings.googleOAuthTitle': 'Google Business Profile (OAuth)',
    'settings.googleOAuthDesc': 'Required to sync reviews from Google and post replies. Separate from the Places API key above. Link each store to Google in Listings using Place ID.',
    'settings.saveBtn': 'Save Configuration',
    'settings.saving': 'Saving...',
    'settings.success': 'Settings saved successfully.',
    'settings.error': 'Failed to save settings.',
    'settings.teamMembers': 'Team Members',
    'settings.teamMembersDesc': 'Manage who has access to your business dashboard.',
    'settings.enterEmail': 'Enter email address',
    'settings.addMember': 'Add Member',
    'settings.noMembers': 'No team members added yet.',
    'settings.added': 'Added',
    'settings.removeMember': 'Remove member',

    // Reports
    'reports.title': 'GBP Performance Report',
    'reports.subtitle': 'Visualize search visibility, map interactions, and customer actions for your business listings.',
    'reports.source': 'Source',
    'reports.allLocations': 'All Locations',
    'reports.startDate': 'Start Date',
    'reports.endDate': 'End Date',
    'reports.downloadPdf': 'Download PDF Report',
    'reports.generating': 'Generating...',
    'reports.loading': 'Loading report data...',
    'reports.noData': 'No data available',
    'reports.noDataHint': 'Make sure your Google Business Profile is connected and has activity in this date range.',
    'reports.totalSearchViews': 'Total Search Views',
    'reports.totalMapViews': 'Total Map Views',
    'reports.totalActions': 'Total Actions',
    'reports.phoneCalls': 'Phone Calls',
    'reports.vsPrevPeriod': '% vs previous period',
    'reports.searchPerf': 'Search Performance',
    'reports.trendOverTime': 'Trend Over Time',
    'reports.monthlyBreakdown': 'Monthly Breakdown',
    'reports.period': 'Period',
    'reports.search': 'Search',
    'reports.maps': 'Maps',
    'reports.chg': '% Chg',
    'reports.total': 'Total',
    'reports.searchVsMapShare': 'Search vs Map Share',
    'reports.weeklySearch': 'Weekly Search Performance',
    'reports.actionsPerf': 'Actions Performance',
    'reports.directions': 'Directions',
    'reports.calls': 'Calls',
    'reports.actionsBreakdown': 'Actions Breakdown',
    'reports.weeklyActions': 'Weekly Actions',
    'reports.avgRank': 'Average Rank',
    'reports.across': 'across',
    'reports.points': 'points',
    'reports.top3Positions': 'Top 3 Positions',
    'reports.top10Positions': 'Top 10 Positions',
    'reports.ofAllPoints': 'of all grid points',
    'reports.pointsScanned': 'Points Scanned',
    'reports.gridPoints': 'grid points',
    'reports.searchGridMap': 'Search Grid Map',
    'reports.keyword': 'Keyword',
    'reports.gridPointsAround': 'grid points around',
    'reports.rank1to3': 'Rank 1-3',
    'reports.rank4to10': 'Rank 4-10',
    'reports.rank11plus': 'Rank 11+',
    'reports.noData2': 'No data',
    'reports.results': 'results',
    'reports.notFound': 'Not found',
    'reports.yourRankHere': 'Your rank here',
    'reports.totalResults': 'Total results',
    'reports.coordinates': 'Coordinates',
    'reports.competitorsVisible': 'Competitors visible',
    'reports.topCompetitors': 'Top Competitors at This Point',
    'reports.noCompetitorData': 'No competitor data for this point.',
    'reports.allGridPoints': 'All Grid Points',
    'reports.point': 'Point',
    'reports.yourRank': 'Your Rank',
    'reports.results2': 'Results',
    'reports.topCompetitor': 'Top Competitor',
    'reports.notRanked': 'Not ranked',
    'reports.reviews': 'reviews',
    'reports.localSearchGrid': 'Local Search Grid',
    'reports.localSearchGridDesc': 'Visualize rankings on a geographical map to identify local opportunities and track competitor performance.',
    'reports.createReport': 'Create report',
    'reports.keywordQuery': 'Keyword / Query',
    'reports.keywordPlaceholder': 'e.g. "mini bowl" or "restaurant near me"',
    'reports.scanning': 'Scanning...',
    'reports.noCoords': 'No location coordinates found. Please connect a Google Business Profile listing with coordinates.',
    'reports.rankingCompetitors': 'Ranking competitors',
    'reports.rankingCompetitorsDesc': 'Top-performing search competitors, based on the Grid Points for this keyword',
    'reports.noDataYet': 'No data available yet. Create your first report to start tracking your local ranking performance against competitors.',
    'reports.seoOptimization': 'SEO optimization:',
    'reports.reportSettings': 'Report settings',
    'reports.generateOptReport': 'Generate an optimization report. Get a guide on how to increase your ranking on Google and much more.',
    'reports.periodLastWeek': 'Period: Last week',
    'reports.periodLastMonth': 'Period: Last month',
    'reports.periodLast3Months': 'Period: Last 3 months',
    'reports.generateReport': 'Generate report',
    'reports.credits': 'credits',
    'reports.gridPointDetails': 'Grid Point',
    'reports.you': 'You',
    'reports.downloadFailed': 'PDF download failed',
    'reports.seoHealthScore': 'SEO Health Score',
    'reports.quickWins': 'Quick Wins',
    'reports.keyInsights': 'Key Optimization Insights',
    'reports.competitiveOpp': 'Competitive Opportunities',
    'reports.analyzing': 'Analyzing...',
    'reports.recommendations': 'recommendations',
    'reports.current': 'Current',
    'reports.suggested': 'Suggested',
    'reports.potentialImpact': 'Potential Impact',
    'reports.updateCategories': 'Update Categories',
    'reports.updateDescription': 'Update Description',
    'reports.high': 'High',
    'reports.medium': 'Medium',
    'reports.low': 'Low',
    'reports.impact': 'Impact',
    'reports.effort': 'Effort',
    'reports.actionSteps': 'Action Steps',
    'reports.generateSeoReport': 'Generate SEO Report',

    // SEO
    'seo.localSearchGrid': 'Local search grid',
    'seo.localCitations': 'Local citations',
    'seo.optimization': 'Optimization',
    'seo.loading': 'Loading SEO data...',
    'seo.keywords': 'Keywords',
    'seo.localCitation': 'Local citation:',
    'seo.localSeo': 'Local SEO',
    'seo.baselineInfo': 'Baseline information (Google)',
    'seo.businessHours': 'Business Hours',
    'seo.name': 'Name',
    'seo.status': 'Status',
    'seo.address': 'Address',
    'seo.hours': 'Hours',
    'seo.phone': 'Phone',
    'seo.lastUpdate': 'Last update:',
    'seo.notYourBusiness': 'Not your business?',
    'seo.matched': 'Matched',
    'seo.mismatch': 'Mismatch',

    // SEO Section Headers
    'seo.section.localSeo': 'Local SEO',
    'seo.section.realComment': 'Real Comment',
    'seo.section.rednoteSeo': 'Rednote SEO',
    'seo.section.localSeoDesc': 'Track rankings, citations, and optimization',
    'seo.section.realCommentDesc': 'Generate authentic reviews via managed Google accounts',
    'seo.section.rednoteSeoDesc': 'Create Xiaohongshu posts with AI assistance',

    // Real Comment
    'realComment.connectedAccounts': 'Connected Google Accounts',
    'realComment.connectNew': 'Connect Google Account',
    'realComment.disconnect': 'Disconnect',
    'realComment.accountsConnected': 'accounts connected',
    'realComment.noAccounts': 'No Google accounts connected yet',
    'realComment.noAccountsDesc': 'Connect your managed Google accounts to start generating authentic reviews for your business.',
    'realComment.selectAccount': 'Select Account',
    'realComment.writeReview': 'Write Review',
    'realComment.selectLocation': 'Target Location',
    'realComment.allLocations': 'All Locations',
    'realComment.reviewContent': 'Review Content',
    'realComment.reviewPlaceholder': 'Write your authentic review here...',
    'realComment.generateAIPhoto': 'AI Generate Photo',
    'realComment.photoGallery': 'Photo Gallery',
    'realComment.addPhoto': 'Add Photo',
    'realComment.removePhoto': 'Remove',
    'realComment.rating': 'Rating',
    'realComment.submitReview': 'Submit Review',
    'realComment.saving': 'Saving...',
    'realComment.successSaved': 'Review saved successfully!',
    'realComment.errorNoAccount': 'Please select a Google account first',
    'realComment.errorNoContent': 'Please write some review content',
    'realComment.recentReviews': 'Recent Reviews',
    'realComment.reviewHistory': 'Review History',
    'realComment.status': 'Status',
    'realComment.pending': 'Pending',
    'realComment.published': 'Published',
    'realComment.failed': 'Failed',
    'realComment.account': 'Account',
    'realComment.location': 'Location',
    'realComment.date': 'Date',
    'realComment.content': 'Content',
    'realComment.noReviewHistory': 'No review history yet',
    'realComment.createReview': 'Create Review',
    'realComment.submitting': 'Submitting...',
    'realComment.completed': 'Completed',
    'realComment.successSubmitted': 'Review submitted successfully!',

    // RedNote SEO
    'rednote.account': 'Account',
    'rednote.accountManagement': 'Account Management',
    'rednote.accountStatus': 'Account Status',
    'rednote.accountStatusTitle': 'Account Status',
    'rednote.connectAccount': 'Connect Xiaohongshu Account',
    'rednote.login': 'Login',
    'rednote.logout': 'Logout',
    'rednote.loginFromChrome': 'Login from Chrome',
    'rednote.loginSuccess': 'Login successful!',
    'rednote.loginFailed': 'Login failed',
    'rednote.notInstalled': 'XHS CLI Not Installed',
    'rednote.notInstalledDesc': 'Please run the following command on your server:',
    'rednote.installCommand': 'uv tool install xiaohongshu-cli',
    'rednote.notLoggedIn': 'Not Logged In',
    'rednote.notLoggedInDesc': 'Click the button below to extract cookies from Chrome browser and login',
    'rednote.followers': 'Followers',
    'rednote.following': 'Following',
    'rednote.likes': 'Likes',
    'rednote.refresh': 'Refresh',
    'rednote.myNotes': 'My Notes',
    'rednote.noNotes': 'No notes yet, go publish your first one!',
    'rednote.dataOverview': 'Data Overview',
    'rednote.notesPublished': 'Published Notes',
    'rednote.totalLikes': 'Total Likes',
    'rednote.totalCollections': 'Total Collections',
    'rednote.totalComments': 'Total Comments',
    'rednote.syncing': 'Syncing...',
    'rednote.noNotesYet': 'No notes yet',
    'rednote.goPublishFirst': 'Go publish your first note!',
    'rednote.defaultNickname': 'Xiaohongshu User',
    'rednote.redId': 'Red ID:',
    'rednote.aiSmartGenerate': 'AI Smart Generate',
    'rednote.editContent': 'Edit Content',
    'rednote.contentTitle': 'Title',
    'rednote.titlePlaceholder': 'Enter note title...',
    'rednote.contentBody': 'Content',
    'rednote.bodyPlaceholder': 'Enter note content...',
    'rednote.topics': 'Topics',
    'rednote.imageUpload': 'Image',
    'rednote.imageCount': 'Images ({count}/9)',
    'rednote.imageHint': 'Drag images or click to upload',
    'rednote.clear': 'Clear',
    'rednote.publishing': 'Publishing...',
    'rednote.publishBtn': 'Publish',
    'rednote.publishSuccess': 'Published successfully!',
    'rednote.publishFailed': 'Publish failed',
    'rednote.deleteSuccess': 'Deleted successfully',
    'rednote.deleteFailed': 'Delete failed',
    'rednote.titleBodyRequired': 'Title and content cannot be empty',
    'rednote.copySuccess': 'Copied to clipboard',
    'rednote.searchNotes': 'Search Notes',
    'rednote.searchPlaceholder': 'Enter keywords...',
    'rednote.noTitle': 'No title',
    'rednote.commentDetail': 'Comment Detail',
    'rednote.selectNote': 'Select a note',
    'rednote.selectNoteHint': 'Search and select a note from the left to view comments',
    'rednote.noComments': 'No comments yet',
    'rednote.anonymousUser': 'Anonymous',
    'rednote.replyPlaceholder': 'Enter reply...',
    'rednote.brandMonitor': 'Brand Monitor',
    'rednote.brandPlaceholder': 'Enter brand/competitor keywords...',
    'rednote.recent': 'Recent:',
    'rednote.relatedNotes': '{count} related notes found',
    'rednote.topicHeat': 'Topic Heat',
    'rednote.topicPlaceholder': 'Enter topic keywords...',
    'rednote.unknownTopic': 'Unknown topic',
    'rednote.notes': 'notes',
    'rednote.likes': 'likes',
    'rednote.comments': 'comments',
    'rednote.searchFailed': 'Search failed',
    'rednote.getCommentsFailed': 'Failed to get comments',
    'rednote.replySuccess': 'Reply posted!',
    'rednote.replyFailed': 'Reply failed',
    'rednote.undoLike': 'Like removed',
    'rednote.liked': 'Liked',
    'rednote.operationFailed': 'Operation failed',
    'rednote.topicSearchFailed': 'Topic search failed',

    'rednote.publish': 'Publish',
    'rednote.publishNote': 'Publish Note',
    'rednote.title': 'Title',
    'rednote.titlePlaceholder': 'Enter note title...',
    'rednote.body': 'Content',
    'rednote.bodyPlaceholder': 'Enter note content...',
    'rednote.topics': 'Topics',
    'rednote.images': 'Images',
    'rednote.imagesDesc': 'Drag images here or click to upload',
    'rednote.imagesLimit': 'Supports JPG, PNG format, up to 9 images',
    'rednote.clear': 'Clear',
    'rednote.publishing': 'Publishing...',
    'rednote.publishSuccess': 'Published successfully!',
    'rednote.publishFailed': 'Publish failed',
    'rednote.deleteNote': 'Delete Note',
    'rednote.confirmDelete': 'Are you sure you want to delete this note?',

    'rednote.aiGenerate': 'AI Generate',
    'rednote.aiGenerating': 'Generating...',
    'rednote.aiGenerated': 'AI content generated',
    'rednote.aiGenerateFailed': 'AI generation failed',
    'rednote.businessName': 'Business/Brand Name',
    'rednote.businessNamePlaceholder': 'Enter business/brand name as reference...',
    'rednote.contentTemplate': 'Content Template',
    'rednote.template.explore': 'Explore & Review',
    'rednote.template.recommend': 'Product Recommend',
    'rednote.template.lifestyle': 'Life Record',
    'rednote.template.tutorial': 'Tutorial Share',

    'rednote.comments': 'Comments',
    'rednote.commentsManagement': 'Comments Management',
    'rednote.searchNotes': 'Search Notes',
    'rednote.searchPlaceholder': 'Enter keywords to search notes...',
    'rednote.noComments': 'No comments yet',
    'rednote.reply': 'Reply',
    'rednote.replyPlaceholder': 'Enter reply...',
    'rednote.replySuccess': 'Reply posted!',
    'rednote.replyFailed': 'Reply failed',

    'rednote.monitor': 'Monitor',
    'rednote.brandMonitor': 'Brand Monitor',
    'rednote.monitorPlaceholder': 'Enter brand/competitor keywords...',
    'rednote.topicSearch': 'Topic Search',
    'rednote.topicSearchPlaceholder': 'Enter topic keywords...',
    'rednote.relatedNotes': 'Related Notes',
    'rednote.topicHeat': 'Topic Heat',
    'rednote.noResults': 'No results found',

    // Workflow steps
    'rednote.step.account': 'Account',
    'rednote.step.publish': 'Publish',
    'rednote.step.comments': 'Comments',
    'rednote.step.monitor': 'Monitor',

    // Page titles
    'rednote.pageTitle': 'Rednote Operations',
    'rednote.pageSubtitle': 'Content creation, account management, and brand monitoring',
    'rednote.loggedIn': 'Logged In',
    'rednote.notLoggedInStatus': 'Not Logged In',

    // Real Comment AI Generation
    'realComment.aiGenerate': 'AI Generate Review',
    'realComment.aiGenerating': 'Generating unique review...',
    'realComment.aiGenerated': 'AI Review Generated!',
    'realComment.aiGenerateNew': 'Generate Another',
    'realComment.aiTip': 'Each generation creates a unique review with different scenarios, personas, and perspectives - all positive reviews.',
    'realComment.identityLabel': 'Reviewing as:',

    // Rednote SEO (Xiaohongshu)
    'rednote.connectAccount': 'Connect Xiaohongshu Account',
    'rednote.disconnectAccount': 'Disconnect',
    'rednote.connected': 'Connected',
    'rednote.notConnected': 'Not Connected',
    'rednote.noAccount': 'No Xiaohongshu account connected',
    'rednote.noAccountDesc': 'Connect your Xiaohongshu account to start creating posts for your business.',
    'rednote.createPost': 'Create Post',
    'rednote.aiGeneratePost': 'AI Generate Post',
    'rednote.aiGenerating': 'Generating post content...',
    'rednote.aiGenerated': 'Post content generated!',
    'rednote.aiGenerateNew': 'Generate Another',
    'rednote.aiTip': 'AI will generate unique Xiaohongshu-style content based on your business info and similar local business posts.',
    'rednote.postTitle': 'Post Title',
    'rednote.postTitlePlaceholder': 'Enter post title...',
    'rednote.postContent': 'Post Content',
    'rednote.postContentPlaceholder': 'Write your post content...',
    'rednote.postTags': 'Tags',
    'rednote.postTagsPlaceholder': 'Add relevant tags',
    'rednote.addTag': 'Add Tag',
    'rednote.photos': 'Photos',
    'rednote.addPhoto': 'Add Photo',
    'rednote.selectLocation': 'Link Location',
    'rednote.preview': 'Preview',
    'rednote.saveDraft': 'Save Draft',
    'rednote.publishNow': 'Publish Now',
    'rednote.schedulePost': 'Schedule Post',
    'rednote.saving': 'Saving...',
    'rednote.successSaved': 'Post saved successfully!',
    'rednote.successPublished': 'Post published successfully!',
    'rednote.errorNoTitle': 'Please enter a post title',
    'rednote.errorNoContent': 'Please enter post content',
    'rednote.recentPosts': 'Recent Posts',
    'rednote.postHistory': 'Post History',
    'rednote.posted': 'Posted',
    'rednote.draft': 'Draft',
    'rednote.scheduled': 'Scheduled',
    'rednote.noPostHistory': 'No posts yet',
    'rednote.noPostHistoryDesc': 'Create your first Xiaohongshu post to promote your business.',

    // Bulk Edits
    'bulkEdits.title': 'Bulk Edits',
    'bulkEdits.subtitle': 'Update multiple business locations simultaneously.',
    'bulkEdits.refresh': 'Refresh',
    'bulkEdits.updateResults': 'Update Results',
    'bulkEdits.updatedSuccess': 'updated successfully',
    'bulkEdits.failed': 'failed',
    'bulkEdits.done': 'Done',
    'bulkEdits.selectLocations': 'Select locations',
    'bulkEdits.noListings': 'No listings found. Make sure EmbedSocial is configured.',
    'bulkEdits.selectAll': 'Select all listings',
    'bulkEdits.deselectAll': 'Deselect All',
    'bulkEdits.selectAll2': 'Select All',
    'bulkEdits.noAddress': 'No address',
    'bulkEdits.chooseFields': 'Choose fields to edit',
    'bulkEdits.enterValues': 'Enter the new values for the fields you want to update...',
    'bulkEdits.nextChooseFields': 'Next: Choose Fields',
    'bulkEdits.back': 'Back',
    'bulkEdits.reviewChanges': 'Review Changes',
    'bulkEdits.completeStep1': 'Complete Step 1 to select fields.',
    'bulkEdits.reviewApply': 'Review & Apply',
    'bulkEdits.summary': 'Summary',
    'bulkEdits.locationsSelected': 'Locations selected:',
    'bulkEdits.fieldsToUpdate': 'Fields to update:',
    'bulkEdits.changes': 'Changes',
    'bulkEdits.applyChanges': 'Apply Changes',
    'bulkEdits.saving': 'Saving...',
    'bulkEdits.completePrevSteps': 'Complete previous steps to review changes.',

    // Edits Log
    'editsLog.title': 'Activity Log',
    'editsLog.subtitle': 'Track all changes and sync activities',
    'editsLog.allActivity': 'All Activity',
    'editsLog.created': 'Created',
    'editsLog.posts': 'Posts',
    'editsLog.replies': 'Replies',
    'editsLog.sync': 'Sync',
    'editsLog.deleted': 'Deleted',
    'editsLog.justNow': 'Just now',
    'editsLog.minsAgo': 'm ago',
    'editsLog.hoursAgo': 'h ago',
    'editsLog.daysAgo': 'd ago',
    'editsLog.noActivity': 'No Activity Yet',
    'editsLog.noActivityDesc': 'Connect listings, send review replies, and create posts to see your activity here.',

    // Publishing
    'publishing.createNewPost': 'Create New Post',
    'publishing.content': 'Content',
    'publishing.contentPlaceholder': 'What would you like to share?',
    'publishing.scheduleOptional': 'Schedule (optional)',
    'publishing.selectLocation': 'Select a location',
    'publishing.cancel': 'Cancel',
    'publishing.creating': 'Creating...',
    'publishing.schedulePost': 'Schedule Post',
    'publishing.saveDraft': 'Save as Draft',
    'publishing.today': 'Today',
    'publishing.published': 'published',
    'publishing.scheduled': 'scheduled',
    'publishing.drafts': 'drafts',
    'publishing.allLocations': 'All Locations',
    'publishing.statusAll': 'Status: All',
    'publishing.published2': 'Published',
    'publishing.scheduled2': 'Scheduled',
    'publishing.draft': 'Draft',
    'publishing.publishNow': 'Publish now',
    'publishing.deletePost': 'Delete post',
    'publishing.scheduledStatus': 'Scheduled',
    'publishing.draftStatus': 'Saved as draft',

    // Help
    'help.helpCenter': 'Help Center',
    'help.helpSubtitle': 'Learn how to set up and use Review Sync App',
    'help.features': 'Features',
    'help.quickSetup': 'Quick Setup Guide',
    'help.faq': 'Frequently Asked Questions',
    'help.feature1': 'Review Management',
    'help.feature1Desc': 'View and manage Google reviews across all locations from one unified inbox.',
    'help.feature2': 'AI-Powered Replies',
    'help.feature2Desc': 'Generate professional responses to customer reviews with a single click.',
    'help.feature3': 'Smart Sync',
    'help.feature3Desc': 'Automatically sync your business listings and review data on a schedule.',
    'help.feature4': 'Publishing',
    'help.feature4Desc': 'Schedule and manage posts to Google Business Profiles.',
    'help.step1': 'Step 1: Connect Your Listings',
    'help.step1Desc': 'Go to Settings > Google Business Listings and click Connect New Listing.',
    'help.step2': 'Step 2: Manage Reviews',
    'help.step2Desc': 'Visit the Reviews tab to view and respond to customer feedback.',
    'help.step3': 'Step 3: Set Up AI Replies',
    'help.step3Desc': 'Configure your Gemini API key in Settings to enable AI reply generation.',
    'help.step4': 'Step 4: Edit Listings',
    'help.step4Desc': 'Edit business information across all locations using Listings or Bulk Edits.',
    'help.faq1': 'How do I get started?',
    'help.faq1Ans': 'Sign in with your Google account, then go to Settings > Google Business Listings to connect your locations.',
    'help.faq2': 'How do I connect my business listings?',
    'help.faq2Ans': 'Go to Settings > Google Business Listings and click Connect New Listing. Follow the Google OAuth flow.',
    'help.faq3': 'Why are my reviews not showing?',
    'help.faq3Ans': 'Make sure you have connected your listings via Google OAuth in Settings. Reviews are synced from Google.',
    'help.faq4': 'How does AI reply generation work?',
    'help.faq4Ans': 'The app uses Gemini AI to generate professional replies based on the review content. Configure your API key in Settings.',
    'help.faq5': 'Can I bulk edit multiple locations?',
    'help.faq5Ans': 'Yes! Go to Bulk Edits, select multiple locations, choose the fields to update, and apply changes.',
    'help.faq6': 'How do I publish posts to Google?',
    'help.faq6Ans': 'Go to Publishing and click Create New Post. Select a location and schedule or publish immediately.',

    // Edit Business Page
    'business.editInfo': 'Edit Business Info',
    'business.updateInfo': 'Update your listing information',
    'business.basicInfo': 'Basic Info',
    'business.hours': 'Hours',
    'business.categories': 'Categories',
    'business.businessDetails': 'Business Details',
    'business.businessName': 'Business Name',
    'business.businessNamePlaceholder': 'Enter business name',
    'business.address': 'Address',
    'business.addressPlaceholder': 'Enter full address',
    'business.phone': 'Phone Number',
    'business.phonePlaceholder': '(555) 123-4567',
    'business.website': 'Website URL',
    'business.websitePlaceholder': 'https://www.example.com',
    'business.currentStats': 'Current Stats',
    'business.avgRating': 'Average Rating',
    'business.totalReviews': 'Total Reviews',
    'business.openingHours': 'Opening Hours',
    'business.enterHours': 'Enter each day\'s hours on a new line',
    'business.addCategory': 'Add',
    'business.noCategories': 'No categories added yet',
    'business.categoryPlaceholder': 'Enter category name',
    'business.saveChanges': 'Save Changes',
    'business.saving': 'Saving...',
    'business.discard': 'Discard',

    // Auth
    'auth.appName': 'Review Sync',
    'auth.appTagline': 'Manage your Google Business reviews',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.name': 'Name',
    'auth.namePlaceholder': 'Your name',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'you@example.com',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Min. 8 characters',
    'auth.submitSignIn': 'Sign In',
    'auth.submitSignUp': 'Create Account',
    'auth.orContinue': 'or continue with',
    'auth.google': 'Google',

    // Optimization
    'opt.loading': 'Loading...',
    'opt.loadingTitle': 'Loading...',
    'opt.initializing': 'Initializing optimization engine...',
    'opt.scanning': 'Scanning business listings',
    'opt.analyzing': 'Analyzing review patterns',
    'opt.checkingCitations': 'Checking citation consistency',
    'opt.generatingRecs': 'Generating recommendations',
    'opt.analyzingAi': 'AI is analyzing your business profile',
    'opt.evaluating': 'Evaluating listings, reviews, citations and more...',
    'opt.startAnalysis': 'Start Analysis',
    'opt.regenerate': 'Regenerate',
    'opt.analyzingWithAi': 'Analyzing with AI...',
    'opt.overview': 'Overview',
    'opt.insights': 'Insights',
    'opt.competitive': 'Competitive',
    'opt.quickWins': 'Quick Wins',
    'opt.recommendations': 'Recommendations',
    'opt.competitorInsights': 'Competitor Insights',
    'opt.highPriority': 'High Priority',
    'opt.all': 'All',
    'opt.high': 'High',
    'opt.med': 'Med',
    'opt.low': 'Low',
    'opt.allGood': 'All Good!',
    'opt.noIssues': 'No issues found for the selected filter.',
    'opt.aiGenerated': 'AI-generated recommendations based on your profile',
    'opt.marketInsights': 'Market insights and strategic opportunities',
    'opt.highImpactLowEffort': 'High impact, low effort optimization actions',
    'opt.marketData': 'No competitive data yet',
    'opt.competitiveGenerated': 'Competitive insights will be generated on next analysis',
    'opt.noQuickWins': 'No quick wins available',
    'opt.quickWinsAppear': 'Quick wins will appear when optimization opportunities are found',
    'opt.takeAction': 'Take Action',
    'opt.recommendation': 'Recommendation',
    'opt.current': 'Current',
    'opt.target': 'Target',
    'opt.potentialImpact': 'Potential Impact',
    'opt.photos': 'Photos',
    'opt.reviews': 'Reviews',
    'opt.description': 'Description',
    'opt.hours': 'Hours',
    'opt.contact': 'Contact',
    'opt.verification': 'Verification',
    'opt.quickWinsSubtitle': 'High impact, low effort actions',
    'opt.viewAll': 'View all',
    'opt.yourRank': 'Your Rank',
    'opt.notRanked': 'Not ranked',
    'opt.results': 'results',
    'opt.actionSteps': 'Action Steps',
    'opt.impact': 'Impact',
    'opt.searchMap': 'Search Map',
    'opt.top3': 'Top 3',
    'opt.top10': 'Top 10',
    'opt.pointsScanned': 'Points Scanned',
    'opt.avgRank': 'Avg Rank',
    'opt.seoHealthScore': 'SEO Health Score',
    'opt.impactHigh': 'High Impact',
    'opt.impactMedium': 'Medium Impact',
    'opt.impactLow': 'Low Impact',
    'app.loading': 'Loading...',
    'app.loadingDesc': 'Getting everything ready',
    'listings.loading': 'Loading listings...',
    'listings.loadingDesc': 'Fetching your business locations',
    'reviews.loading': 'Loading reviews...',
    'reviews.loadingDesc': 'Gathering customer feedback',
    'settings.loading': 'Loading settings...',
    'settings.loadingDesc': 'Retrieving your preferences',
    'automations.loading': 'Loading automations...',
    'automations.loadingDesc': 'Preparing your workflows',
    'realComment.loading': 'Loading...',
    'realComment.loadingDesc': 'Setting up intelligent responses',
    'rednote.checkingAccountStatus': 'Checking Xiaohongshu account status',
  },

  zh: {
    // Navigation
    'nav.dashboard': '仪表盘',
    'nav.listings': '门店管理',
    'nav.reviews': '评价管理',
    'nav.bulkEdits': '批量编辑',
    'nav.editsLog': '编辑日志',
    'nav.publishing': '内容发布',
    'nav.reports': '数据报告',
    'nav.seo': 'SEO优化',
    'nav.localSeo': '本地SEO',
    'nav.realComment': '真实评论',
    'nav.rednoteSeo': '小红书SEO',
    'nav.comments': '评论',
    'nav.posts': '贴文管理',
    'nav.docs': '使用文档',
    'nav.settings': '系统设置',
    'nav.help': '帮助中心',
    'nav.connectBusiness': '连接商家',
    'nav.signOut': '退出登录',
    'nav.profile': '个人资料',
    'nav.changeAvatar': '更换头像',
    'nav.changePassword': '修改密码',
    'nav.language': '语言',
    'nav.theme': '主题',
    'nav.light': '浅色',
    'nav.dark': '深色',
    'nav.salesDoc': '功能说明',

    // Header
    'header.search': '搜索...',
    'header.locations': '门店',
    'header.keywords': '关键词',

    // Comments Gen
    'comments.title': '自动评价',
    'comments.subtitle': '使用您管理的 Google 账号生成并定时发布评价。',
    'comments.quota': '本月额度',
    'comments.remaining': '剩余',
    'comments.setup': '任务设置',
    'comments.selectAccount': '选择账号',
    'comments.targetLocation': '目标门店（可选）',
    'comments.generation': '内容生成',
    'comments.keywords': '关键词 / 上下文',
    'comments.keywordsPlaceholder': '例如：咖啡好喝，服务热情，环境安静',
    'comments.generateBtn': '生成评价',
    'comments.reviewContent': '评价内容',
    'comments.reviewPlaceholder': '生成的评价会显示在这里。您可以在保存前进行修改。',
    'comments.photos': '上传图片（可选）',
    'comments.addPhoto': '添加图片',
    'comments.saveTask': '保存任务到队列',
    'comments.quotaExceeded': '本月额度已用完，无法保存新任务。',
    'comments.errorKeywords': '请先输入关键词。',
    'comments.errorAccount': '请选择一个 Google 账号。',
    'comments.errorContent': '请生成或手动输入评价内容。',
    'comments.success': '评价任务保存成功！已加入执行队列。',

    // App
    'app.title.dashboard': 'PinKernel SEO',
    'app.title.listings': 'PinKernel SEO',
    'app.title.reviews': 'PinKernel SEO',
    'app.title.comments-gen': 'PinKernel SEO',
    'app.title.rank-tracker': 'PinKernel SEO',
    'app.title.posts': 'PinKernel SEO',
    'app.title.reports': 'PinKernel SEO',
    'app.title.keywords': 'PinKernel SEO',
    'app.title.settings': 'PinKernel SEO',
    'app.title.docs': 'PinKernel SEO',
    'app.configWarning': '请配置您的 API 设置以使用该应用程序。',
    'app.goToSettings': '前往设置',
    'dashboard.subtitle': '欢迎回来。以下是您门店今天的最新动态。',
    'dashboard.totalLocations': '总门店数',
    'dashboard.avgRating': '平均评分',
    'dashboard.totalReviews': '总评价数',
    'dashboard.replyRate': '回复率',
    'dashboard.unreplied': '未回复',
    'dashboard.replied': '已回复',
    'dashboard.viewAll': '查看全部',
    'dashboard.traffic': '流量趋势',
    'dashboard.views': '浏览量',
    'dashboard.clicks': '点击量',
    'dashboard.topKeywords': '热门关键词',
    'dashboard.keyword': '关键词',
    'dashboard.rank': '排名',
    'dashboard.volume': '搜索量',
    'dashboard.trend': '趋势',
    'dashboard.recentActivity': '近期动态',
    'dashboard.activity.review': '收到新的 5 星评价',
    'dashboard.activity.post': '贴文自动发布成功',
    'dashboard.activity.sync': '门店数据同步完成',
    'dashboard.quickActions': '快捷操作',
    'dashboard.action.reply': '回复评价',
    'dashboard.action.post': '创建贴文',
    'dashboard.action.sync': '同步数据',
    'dashboard.locationFocus': '重点门店',
    'dashboard.heatmap': '本地可见度热力图',
    'dashboard.updated': '更新于',
    'dashboard.aiSuggestion': 'AI 建议',
    'dashboard.aiSuggestionDesc': 'Arlington 门店有 12 个未回复的问题。立即回复以提升互动率。',
    'dashboard.openAiAssistant': '打开 AI 助手',
    'dashboard.health': '健康度',
    'dashboard.profileCompleteness': '资料完整度',
    'dashboard.businessName': '商家名称',
    'dashboard.address': '地址（位置）',
    'dashboard.website': '网站地址',
    'dashboard.phoneNumber': '电话号码',
    'dashboard.numberOfReviews': '评价数量',
    'dashboard.per100': '/ 100',
    'dashboard.per5': '/ 5',
    'dashboard.reviewsUnit': '条评价',
    'dashboard.performanceOverview': '所有商家门店的表现概览',
    'dashboard.last7Days': '最近7天',
    'dashboard.last30Days': '最近30天',
    'dashboard.last90Days': '最近90天',
    'dashboard.last12Months': '最近12个月',
    'dashboard.searchViews': '搜索展示',
    'dashboard.mapViews': '地图展示',
    'dashboard.websiteClicks': '网站点击',
    'dashboard.directionRequests': '导航请求',
    'dashboard.phoneCalls': '电话拨打',
    'dashboard.publishedPosts': '已发布贴文',
    'dashboard.overviewImpressions': '概览：展示',
    'dashboard.impressionsDesc': '搜索展示和地图展示的时间趋势',
    'dashboard.overviewActions': '概览：互动',
    'dashboard.actionsDesc': '网站点击、导航请求和电话拨打的时间趋势',
    'dashboard.all': '全部',
    'dashboard.positive': '正面',
    'dashboard.negative': '负面',
    'dashboard.noReviewsYet': '暂无评价',
    'dashboard.reviewTrends': '评价趋势',
    'dashboard.newReviewsVsResponses': '新增评价与回复的时间趋势',
    'dashboard.excellent': '优秀',
    'dashboard.good': '良好',
    'dashboard.needsAttention': '需要关注',
    'dashboard.poor': '较差',
    'dashboard.averPostingTime': '平均发帖时间',
    'dashboard.averResponseTime': '平均回复时间',
    'dashboard.responsePct': '回复率',
    'dashboard.loadingData': '正在加载仪表盘数据...',
    'dashboard.selectPeriod': '选择周期',
    'dashboard.recentReviews': '近期评价',
    'dashboard.allLocations': '全部门店',
    'dashboard.noDataAvailable': '暂无数据',

    // Listings
    'listings.title': '门店与资料',
    'listings.subtitle': '管理您所有门店的商业信息。',
    'listings.syncAll': '全部同步',
    'listings.addLocation': '添加门店',
    'listings.search': '搜索门店...',
    'listings.status.synced': '已同步',
    'listings.status.pending': '待同步',
    'listings.table.name': '名称',
    'listings.table.address': '地址',
    'listings.table.phone': '电话',
    'listings.table.status': '状态',
    'listings.table.actions': '操作',
    'listings.edit': '编辑',
    'listings.view': '查看',
    'listings.editor': '商家信息编辑器',
    'listings.noLocations': '未找到门店',
    'listings.noLocationsDesc': '连接您的 Google 商家资料并同步，即可在此处查看和编辑您的门店。',
    'listings.connectGoogle': '连接 Google 账号',
    'listings.businessHours': '营业时间',
    'listings.days.monday': '星期一',
    'listings.days.tuesday': '星期二',
    'listings.days.wednesday': '星期三',
    'listings.days.thursday': '星期四',
    'listings.days.friday': '星期五',
    'listings.days.saturday': '星期六',
    'listings.days.sunday': '星期日',
    'listings.discard': '放弃更改',
    'listings.save': '保存资料',
    'listings.mapPresence': '地图展示',
    'listings.verifiedPosition': '已验证位置',
    'listings.searchPerformance': '搜索表现',
    'listings.directSearches': '直接搜索',
    'listings.discoverySearches': '发现搜索',
    'listings.viewAnalytics': '查看详细分析',

    // Reviews
    'reviews.title': '统一收件箱',
    'reviews.subtitle': '管理并回复所有门店的客户评价。',
    'reviews.filter.all': '全部评价',
    'reviews.filter.unreplied': '未回复',
    'reviews.filter.replied': '已回复',
    'reviews.search': '搜索评价...',
    'reviews.replyBtn': '回复',
    'reviews.aiReplyBtn': 'AI 智能回复',
    'reviews.repliedBy': '回复人',
    'reviews.aiGenerated': 'AI 生成',
    'reviews.syncReviews': '同步评价',
    'reviews.filter': '筛选',
    'reviews.noReviews': '未找到评价。',
    'reviews.noReviewsDesc': '点击"同步评价"从 Google 获取。',
    'reviews.noComment': '未提供评论。',
    'reviews.googleVerified': 'Google 验证评价',
    'reviews.posted': '发布于',
    'reviews.replied': '已回复',
    'reviews.respondToReview': '回复评价',
    'reviews.replyPlaceholder': '写下您的个性化回复...',
    'reviews.readyToSend': '准备发送',
    'reviews.sendReply': '发送回复',
    'reviews.selectReview': '选择一条评价以查看详情',
    'reviews.noReviewsAvailable': '暂无评价',
    'listings.placesApiKeyBanner': '需要 Google Places API 密钥。请在"系统设置 → Google 商家资料"区块顶部填写，或在 .env 中设置 GOOGLE_PLACES_API_KEY。',
    'listings.placesApiKeyManualError': '请在"系统设置 → Google 商家资料"区块顶部填写 Google Places API 密钥，或在 .env 中设置 GOOGLE_PLACES_API_KEY。',

    // Settings
    'settings.title': 'API 设置',
    'settings.subtitle': '配置您的 API 密钥以连接本地业务数据。这些密钥将被安全存储，并用于同步您的门店和评价。',
    'settings.googleApi': 'Google 商家资料 API',
    'settings.googleClientId': 'Google 客户端 ID',
    'settings.googleClientSecret': 'Google 客户端密钥',
    'settings.geminiApi': 'Google Gemini API',
    'settings.geminiApiKey': 'Gemini API 密钥',
    'settings.googlePlacesApiKey': 'Google Places API 密钥',
    'settings.googlePlacesSectionTitle': 'Google Places API',
    'settings.googlePlacesApiKeyDesc': '用于在"门店管理"中搜索并校验 Google 商家地点。与下方 OAuth（商家资料同步）是两套配置。',
    'settings.googlePlacesApiKeyHint': '在 Google Cloud 控制台启用 Places API，再创建 API 密钥（生产环境建议限制为仅 Places）。',
    'settings.googleOAuthTitle': 'Google 商家资料（OAuth 登录）',
    'settings.googleOAuthDesc': '用于从 Google 同步评价并发布回复，与上方的 Places API 密钥不同。在"门店管理"里用 Place ID 关联门店后即可同步。',
    'settings.saveBtn': '保存配置',
    'settings.saving': '保存中...',
    'settings.success': '设置保存成功。',
    'settings.error': '保存设置失败。',
    'settings.teamMembers': '团队成员',
    'settings.teamMembersDesc': '管理谁可以访问您的业务仪表盘。',
    'settings.enterEmail': '输入邮箱地址',
    'settings.addMember': '添加成员',
    'settings.noMembers': '暂无团队成员。',
    'settings.added': '添加于',
    'settings.removeMember': '移除成员',

    // Reports
    'reports.title': 'GBP 业绩报告',
    'reports.subtitle': '可视化您的商家资料的搜索可见度、地图互动和客户行为数据。',
    'reports.source': '来源',
    'reports.allLocations': '全部门店',
    'reports.startDate': '开始日期',
    'reports.endDate': '结束日期',
    'reports.downloadPdf': '下载 PDF 报告',
    'reports.generating': '生成中...',
    'reports.loading': '正在加载报告数据...',
    'reports.noData': '暂无数据',
    'reports.noDataHint': '请确认已连接 Google 商家资料，且在所选日期范围内有相关活动。',
    'reports.totalSearchViews': '搜索展示总次数',
    'reports.totalMapViews': '地图展示总次数',
    'reports.totalActions': '互动总次数',
    'reports.phoneCalls': '电话拨打',
    'reports.vsPrevPeriod': '较上期变化',
    'reports.searchPerf': '搜索表现',
    'reports.trendOverTime': '时间趋势',
    'reports.monthlyBreakdown': '月度明细',
    'reports.period': '周期',
    'reports.search': '搜索',
    'reports.maps': '地图',
    'reports.chg': '变化',
    'reports.total': '合计',
    'reports.searchVsMapShare': '搜索与地图占比',
    'reports.weeklySearch': '每周搜索表现',
    'reports.actionsPerf': '互动表现',
    'reports.directions': '导航请求',
    'reports.calls': '电话',
    'reports.actionsBreakdown': '互动分类',
    'reports.weeklyActions': '每周互动',
    'reports.avgRank': '平均排名',
    'reports.across': '共',
    'reports.points': '个点',
    'reports.top3Positions': '前3名占比',
    'reports.top10Positions': '前10名占比',
    'reports.ofAllPoints': '所有网格点',
    'reports.pointsScanned': '已扫描点数',
    'reports.gridPoints': '个网格点',
    'reports.searchGridMap': '搜索网格地图',
    'reports.keyword': '关键词',
    'reports.gridPointsAround': '个网格点，环绕',
    'reports.rank1to3': '排名 1-3',
    'reports.rank4to10': '排名 4-10',
    'reports.rank11plus': '排名 11+',
    'reports.noData2': '暂无数据',
    'reports.results': '条结果',
    'reports.notFound': '未找到',
    'reports.yourRankHere': '此处您的排名',
    'reports.totalResults': '总结果数',
    'reports.coordinates': '坐标',
    'reports.competitorsVisible': '可见竞品数',
    'reports.topCompetitors': '此点前5竞品',
    'reports.noCompetitorData': '此点暂无竞品数据。',
    'reports.allGridPoints': '全部网格点',
    'reports.point': '网格点',
    'reports.yourRank': '您的排名',
    'reports.results2': '结果数',
    'reports.topCompetitor': '头部竞品',
    'reports.notRanked': '未上榜',
    'reports.reviews': '条评价',
    'reports.localSearchGrid': '本地搜索网格',
    'reports.localSearchGridDesc': '在地理地图上可视化排名，识别本地机会并追踪竞争对手表现。',
    'reports.createReport': '生成报告',
    'reports.keywordQuery': '关键词 / 搜索词',
    'reports.keywordPlaceholder': '例如："小碗菜" 或 "附近的餐厅"',
    'reports.scanning': '扫描中...',
    'reports.noCoords': '未找到位置坐标。请连接带有坐标的 Google 商家资料。',
    'reports.rankingCompetitors': '排名竞品',
    'reports.rankingCompetitorsDesc': '基于该关键词网格点，表现最佳的搜索竞争对手',
    'reports.noDataYet': '暂无数据。生成您的第一份报告，开始追踪本地排名表现与竞争对手。',
    'reports.seoOptimization': 'SEO 优化：',
    'reports.reportSettings': '报告设置',
    'reports.generateOptReport': '生成优化报告，获得提升 Google 排名等详细指南。',
    'reports.periodLastWeek': '周期：最近一周',
    'reports.periodLastMonth': '周期：最近一月',
    'reports.periodLast3Months': '周期：最近三月',
    'reports.generateReport': '生成报告',
    'reports.credits': '积分',
    'reports.gridPointDetails': '网格点详情',
    'reports.you': '您',
    'reports.downloadFailed': 'PDF 下载失败',
    'reports.seoHealthScore': 'SEO 健康评分',
    'reports.quickWins': '快速优化',
    'reports.keyInsights': '关键优化洞察',
    'reports.competitiveOpp': '竞争优势机会',
    'reports.analyzing': 'AI 分析中...',
    'reports.recommendations': '条优化建议',
    'reports.current': '当前状态',
    'reports.suggested': '建议值',
    'reports.potentialImpact': '潜在影响',
    'reports.updateCategories': '更新分类',
    'reports.updateDescription': '更新描述',
    'reports.high': '高',
    'reports.medium': '中',
    'reports.low': '低',
    'reports.impact': '影响',
    'reports.effort': '投入',
    'reports.actionSteps': '操作步骤',

    // SEO
    'seo.localSearchGrid': '本地搜索网格',
    'seo.localCitations': '本地引用',
    'seo.optimization': '优化',
    'seo.loading': '正在加载 SEO 数据...',
    'seo.keywords': '关键词',
    'seo.localCitation': '本地引用：',
    'seo.localSeo': '本地SEO',
    'seo.baselineInfo': '基准信息（Google）',
    'seo.businessHours': '营业时间',
    'seo.name': '名称',
    'seo.status': '状态',
    'seo.address': '地址',
    'seo.hours': '时间',
    'seo.phone': '电话',
    'seo.lastUpdate': '最后更新：',
    'seo.notYourBusiness': '这不是您的商家？',
    'seo.matched': '匹配',
    'seo.mismatch': '不匹配',

    // SEO Section Headers
    'seo.section.localSeo': '本地SEO',
    'seo.section.realComment': '真实评价',
    'seo.section.rednoteSeo': '小红书SEO',
    'seo.section.localSeoDesc': '追踪排名、引用和优化',
    'seo.section.realCommentDesc': '通过管理的 Google 账号生成真实评价',
    'seo.section.rednoteSeoDesc': '使用 AI 辅助创建小红书帖子',

    // Real Comment
    'realComment.connectedAccounts': '已连接的 Google 账号',
    'realComment.connectNew': '连接 Google 账号',
    'realComment.disconnect': '断开连接',
    'realComment.accountsConnected': '个账号已连接',
    'realComment.noAccounts': '暂无 Google 账号连接',
    'realComment.noAccountsDesc': '连接您管理的 Google 账号，开始为您的商家生成真实评价。',
    'realComment.selectAccount': '选择账号',
    'realComment.writeReview': '撰写评价',
    'realComment.selectLocation': '目标门店',
    'realComment.allLocations': '所有门店',
    'realComment.reviewContent': '评价内容',
    'realComment.reviewPlaceholder': '在此撰写您的真实评价...',
    'realComment.generateAIPhoto': 'AI 生成图片',
    'realComment.photoGallery': '图片库',
    'realComment.addPhoto': '添加图片',
    'realComment.removePhoto': '移除',
    'realComment.rating': '评分',
    'realComment.submitReview': '提交评价',
    'realComment.saving': '保存中...',
    'realComment.successSaved': '评价保存成功！',
    'realComment.errorNoAccount': '请先选择一个 Google 账号',
    'realComment.errorNoContent': '请输入评价内容',
    'realComment.recentReviews': '最近评价',
    'realComment.reviewHistory': '评价历史',
    'realComment.status': '状态',
    'realComment.pending': '待发布',
    'realComment.published': '已发布',
    'realComment.failed': '失败',
    'realComment.account': '账号',
    'realComment.location': '门店',
    'realComment.date': '日期',
    'realComment.content': '内容',
    'realComment.noReviewHistory': '暂无评价历史',
    'realComment.createReview': '创建评价',
    'realComment.submitting': '提交中...',
    'realComment.completed': '已完成',
    'realComment.successSubmitted': '评价提交成功！',

    // RedNote SEO
    'rednote.account': '账号',
    'rednote.accountManagement': '账号管理',
    'rednote.accountStatus': '账号状态',
    'rednote.accountStatusTitle': '账号状态',
    'rednote.connectAccount': '连接小红书账号',
    'rednote.login': '登录',
    'rednote.logout': '退出登录',
    'rednote.loginFromChrome': '从 Chrome 登录',
    'rednote.loginSuccess': '登录成功！',
    'rednote.loginFailed': '登录失败',
    'rednote.notInstalled': 'XHS CLI 未安装',
    'rednote.notInstalledDesc': '请在服务器上运行以下命令：',
    'rednote.installCommand': 'uv tool install xiaohongshu-cli',
    'rednote.notLoggedIn': '未登录',
    'rednote.notLoggedInDesc': '点击下方按钮从 Chrome 浏览器提取 Cookie 登录',
    'rednote.followers': '粉丝',
    'rednote.following': '关注',
    'rednote.likes': '获赞',
    'rednote.refresh': '刷新',
    'rednote.myNotes': '我的笔记',
    'rednote.noNotes': '暂无笔记，快去发布第一篇吧！',
    'rednote.dataOverview': '数据概览',
    'rednote.notesPublished': '发布笔记',
    'rednote.totalLikes': '总点赞',
    'rednote.totalCollections': '总收藏',
    'rednote.totalComments': '总评论',
    'rednote.syncing': '同步中',
    'rednote.noNotesYet': '暂无笔记',
    'rednote.goPublishFirst': '去发布第一篇笔记吧！',
    'rednote.defaultNickname': '小红书用户',
    'rednote.redId': '小红书号：',
    'rednote.aiSmartGenerate': 'AI 智能生成',
    'rednote.editContent': '编辑内容',
    'rednote.contentTitle': '标题',
    'rednote.titlePlaceholder': '输入笔记标题...',
    'rednote.contentBody': '正文内容',
    'rednote.bodyPlaceholder': '输入笔记正文内容...',
    'rednote.topics': '话题标签',
    'rednote.imageUpload': '图片',
    'rednote.imageCount': '图片 ({count}/9)',
    'rednote.imageHint': '拖拽图片或点击上传',
    'rednote.clear': '清空',
    'rednote.publishing': '发布中...',
    'rednote.publishBtn': '发布',
    'rednote.publishSuccess': '发布成功！',
    'rednote.publishFailed': '发布失败',
    'rednote.deleteSuccess': '删除成功',
    'rednote.deleteFailed': '删除失败',
    'rednote.titleBodyRequired': '标题和正文不能为空',
    'rednote.copySuccess': '已复制到剪贴板',
    'rednote.searchNotes': '搜索笔记',
    'rednote.searchPlaceholder': '输入关键词搜索...',
    'rednote.noTitle': '无标题',
    'rednote.commentDetail': '评论详情',
    'rednote.selectNote': '选择一篇笔记',
    'rednote.selectNoteHint': '从左侧搜索并选择笔记查看评论',
    'rednote.noComments': '暂无评论',
    'rednote.anonymousUser': '匿名用户',
    'rednote.replyPlaceholder': '输入回复...',
    'rednote.brandMonitor': '品牌监控',
    'rednote.brandPlaceholder': '输入品牌/竞品关键词...',
    'rednote.recent': '最近：',
    'rednote.relatedNotes': '找到 {count} 篇相关笔记',
    'rednote.topicHeat': '话题热度',
    'rednote.topicPlaceholder': '输入话题关键词...',
    'rednote.unknownTopic': '未知话题',
    'rednote.notes': '笔记',
    'rednote.likes': '赞',
    'rednote.comments': '评论',
    'rednote.searchFailed': '搜索失败',
    'rednote.getCommentsFailed': '获取评论失败',
    'rednote.replySuccess': '回复成功！',
    'rednote.replyFailed': '回复失败',
    'rednote.undoLike': '已取消点赞',
    'rednote.liked': '已点赞',
    'rednote.operationFailed': '操作失败',
    'rednote.topicSearchFailed': '话题搜索失败',

    'rednote.publish': '发布',
    'rednote.publishNote': '发布笔记',
    'rednote.title': '标题',
    'rednote.titlePlaceholder': '输入笔记标题...',
    'rednote.body': '正文内容',
    'rednote.bodyPlaceholder': '输入笔记正文内容...',
    'rednote.topics': '话题标签',
    'rednote.images': '图片上传',
    'rednote.imagesDesc': '拖拽图片到此处，或点击上传',
    'rednote.imagesLimit': '支持 JPG、PNG 格式，最多 9 张',
    'rednote.clear': '清空',
    'rednote.publishing': '发布中...',
    'rednote.publishSuccess': '发布成功！',
    'rednote.publishFailed': '发布失败',
    'rednote.deleteNote': '删除笔记',
    'rednote.confirmDelete': '确定要删除这篇笔记吗？',

    'rednote.aiGenerated': 'AI内容已生成',
    'rednote.aiGenerateFailed': 'AI生成失败',
    'rednote.businessName': '商家/品牌名称',
    'rednote.businessNamePlaceholder': '输入商家/品牌名称作为参考...',
    'rednote.contentTemplate': '内容模板',
    'rednote.template.explore': '探店分享',
    'rednote.template.recommend': '好物推荐',
    'rednote.template.lifestyle': '生活记录',
    'rednote.template.tutorial': '教程分享',

    'rednote.comments': '评论',
    'rednote.commentsManagement': '评论管理',
    'rednote.searchNotes': '搜索笔记',
    'rednote.searchPlaceholder': '输入关键词搜索笔记...',
    'rednote.noComments': '暂无评论',
    'rednote.reply': '回复',
    'rednote.replyPlaceholder': '输入回复...',
    'rednote.replySuccess': '回复成功！',
    'rednote.replyFailed': '回复失败',

    'rednote.monitor': '监控',
    'rednote.brandMonitor': '品牌监控',
    'rednote.monitorPlaceholder': '输入品牌/竞品关键词...',
    'rednote.topicSearch': '话题热度',
    'rednote.topicSearchPlaceholder': '输入话题关键词...',
    'rednote.relatedNotes': '相关笔记',
    'rednote.topicHeat': '话题热度',
    'rednote.noResults': '暂无结果',

    // Workflow steps
    'rednote.step.account': '账号',
    'rednote.step.publish': '发布',
    'rednote.step.comments': '评论',
    'rednote.step.monitor': '监控',

    // Page titles
    'rednote.pageTitle': '小红书运营',
    'rednote.pageSubtitle': '内容创作、账号管理与品牌监控',
    'rednote.loggedIn': '已登录',
    'rednote.notLoggedInStatus': '未登录',

    // Real Comment AI Generation
    'realComment.aiGenerate': 'AI 生成评价',
    'realComment.aiGenerating': '正在生成独特评价...',
    'realComment.aiGenerated': 'AI 评价已生成！',
    'realComment.aiGenerateNew': '再生成一条',
    'realComment.aiTip': '每次生成都会创建独特评价，包含不同场景、身份和视角 - 全部为正面评价。',
    'realComment.identityLabel': '评价身份：',

    // Rednote SEO (小红书)
    'rednote.connectAccount': '连接小红书账号',
    'rednote.disconnectAccount': '断开连接',
    'rednote.connected': '已连接',
    'rednote.notConnected': '未连接',
    'rednote.noAccount': '暂无小红书账号连接',
    'rednote.noAccountDesc': '连接您的小红书账号，开始为您的商家创建帖子。',
    'rednote.createPost': '创建帖子',
    'rednote.aiGeneratePost': 'AI 生成帖子',
    'rednote.aiGenerating': '正在生成帖子内容...',
    'rednote.aiGenerated': '帖子内容已生成！',
    'rednote.aiGenerateNew': '再生成一条',
    'rednote.aiTip': 'AI 将根据店面信息和小红书同类店铺的帖子风格，生成独特的小红书风格内容。',
    'rednote.postTitle': '帖子标题',
    'rednote.postTitlePlaceholder': '输入帖子标题...',
    'rednote.postContent': '帖子内容',
    'rednote.postContentPlaceholder': '撰写您的帖子内容...',
    'rednote.postTags': '标签',
    'rednote.postTagsPlaceholder': '添加相关标签',
    'rednote.addTag': '添加标签',
    'rednote.photos': '图片',
    'rednote.addPhoto': '添加图片',
    'rednote.selectLocation': '关联门店',
    'rednote.preview': '预览',
    'rednote.saveDraft': '保存草稿',
    'rednote.publishNow': '立即发布',
    'rednote.schedulePost': '定时发布',
    'rednote.saving': '保存中...',
    'rednote.successSaved': '帖子保存成功！',
    'rednote.successPublished': '帖子发布成功！',
    'rednote.errorNoTitle': '请输入帖子标题',
    'rednote.errorNoContent': '请输入帖子内容',
    'rednote.recentPosts': '最近帖子',
    'rednote.postHistory': '帖子历史',
    'rednote.posted': '已发布',
    'rednote.draft': '草稿',
    'rednote.scheduled': '定时',
    'rednote.noPostHistory': '暂无帖子',
    'rednote.noPostHistoryDesc': '创建您的第一条小红书帖子来推广您的商家。',

    // Bulk Edits
    'bulkEdits.title': '批量编辑',
    'bulkEdits.subtitle': '同时更新多个商家门店。',
    'bulkEdits.refresh': '刷新',
    'bulkEdits.updateResults': '更新结果',
    'bulkEdits.updatedSuccess': '条更新成功',
    'bulkEdits.failed': '条失败',
    'bulkEdits.done': '完成',
    'bulkEdits.selectLocations': '选择门店',
    'bulkEdits.noListings': '未找到门店。请确认 EmbedSocial 已配置。',
    'bulkEdits.selectAll': '全选门店',
    'bulkEdits.deselectAll': '取消全选',
    'bulkEdits.selectAll2': '全选',
    'bulkEdits.noAddress': '无地址',
    'bulkEdits.chooseFields': '选择要编辑的字段',
    'bulkEdits.enterValues': '输入您要更新的字段值...',
    'bulkEdits.nextChooseFields': '下一步：选择字段',
    'bulkEdits.back': '上一步',
    'bulkEdits.reviewChanges': '审核变更',
    'bulkEdits.completeStep1': '请先完成步骤1以选择门店。',
    'bulkEdits.reviewApply': '审核并应用',
    'bulkEdits.summary': '摘要',
    'bulkEdits.locationsSelected': '已选门店：',
    'bulkEdits.fieldsToUpdate': '待更新字段：',
    'bulkEdits.changes': '变更',
    'bulkEdits.applyChanges': '应用变更',
    'bulkEdits.saving': '保存中...',
    'bulkEdits.completePrevSteps': '请完成前面的步骤以审核变更。',

    // Edits Log
    'editsLog.title': '操作日志',
    'editsLog.subtitle': '追踪所有变更和同步活动',
    'editsLog.allActivity': '全部活动',
    'editsLog.created': '创建',
    'editsLog.posts': '贴文',
    'editsLog.replies': '回复',
    'editsLog.sync': '同步',
    'editsLog.deleted': '已删除',
    'editsLog.justNow': '刚刚',
    'editsLog.minsAgo': '分钟前',
    'editsLog.hoursAgo': '小时前',
    'editsLog.daysAgo': '天前',
    'editsLog.noActivity': '暂无活动',
    'editsLog.noActivityDesc': '连接门店、发送评价回复和创建贴文后，即可在此处查看您的活动记录。',

    // Publishing
    'publishing.createNewPost': '创建新贴文',
    'publishing.content': '内容',
    'publishing.contentPlaceholder': '分享您想发布的内容？',
    'publishing.scheduleOptional': '定时发布（可选）',
    'publishing.selectLocation': '选择门店',
    'publishing.cancel': '取消',
    'publishing.creating': '创建中...',
    'publishing.schedulePost': '定时发布',
    'publishing.saveDraft': '保存草稿',
    'publishing.today': '今天',
    'publishing.published': '已发布',
    'publishing.scheduled': '待发布',
    'publishing.drafts': '草稿',
    'publishing.allLocations': '全部门店',
    'publishing.statusAll': '状态：全部',
    'publishing.published2': '已发布',
    'publishing.scheduled2': '待发布',
    'publishing.draft': '草稿',
    'publishing.publishNow': '立即发布',
    'publishing.deletePost': '删除贴文',
    'publishing.scheduledStatus': '已定时',
    'publishing.draftStatus': '已存为草稿',

    // Help
    'help.helpCenter': '帮助中心',
    'help.helpSubtitle': '了解如何设置和使用评价同步应用',
    'help.features': '功能介绍',
    'help.quickSetup': '快速设置指南',
    'help.faq': '常见问题',
    'help.feature1': '评价管理',
    'help.feature1Desc': '通过统一收件箱查看和管理所有门店的 Google 评价。',
    'help.feature2': 'AI 智能回复',
    'help.feature2Desc': '一键生成针对客户评价的专业回复。',
    'help.feature3': '智能同步',
    'help.feature3Desc': '按计划自动同步商家门店和评价数据。',
    'help.feature4': '内容发布',
    'help.feature4Desc': '定时发布和管理 Google 商家资料贴文。',
    'help.step1': '步骤1：连接您的门店',
    'help.step1Desc': '前往"系统设置 > Google 商家资料"，点击"连接新门店"。',
    'help.step2': '步骤2：管理评价',
    'help.step2Desc': '访问"评价管理"标签页，查看并回复客户反馈。',
    'help.step3': '步骤3：设置 AI 回复',
    'help.step3Desc': '在"系统设置"中配置 Gemini API 密钥以启用 AI 回复生成。',
    'help.step4': '步骤4：编辑门店',
    'help.step4Desc': '使用"门店管理"或"批量编辑"编辑所有门店的商家信息。',
    'help.faq1': '如何开始使用？',
    'help.faq1Ans': '使用 Google 账号登录，然后前往"系统设置 > Google 商家资料"连接您的门店。',
    'help.faq2': '如何连接我的商家门店？',
    'help.faq2Ans': '前往"系统设置 > Google 商家资料"，点击"连接新门店"，按提示完成 Google OAuth 授权。',
    'help.faq3': '为什么我的评价没有显示？',
    'help.faq3Ans': '请确认已在"系统设置"中通过 Google OAuth 连接了门店。评价数据从 Google 同步而来。',
    'help.faq4': 'AI 回复生成是如何工作的？',
    'help.faq4Ans': '应用使用 Gemini AI 根据评价内容生成专业回复。请在"系统设置"中配置您的 API 密钥。',
    'help.faq5': '我可以批量编辑多个门店吗？',
    'help.faq5Ans': '可以！前往"批量编辑"，选择多个门店，选择要更新的字段，然后应用变更。',
    'help.faq6': '如何向 Google 发布贴文？',
    'help.faq6Ans': '前往"内容发布"，点击"创建新贴文"，选择门店并设置发布时间或立即发布。',

    // Edit Business Page
    'business.editInfo': '编辑商家信息',
    'business.updateInfo': '更新您的门店资料',
    'business.basicInfo': '基本信息',
    'business.hours': '营业时间',
    'business.categories': '分类',
    'business.businessDetails': '商家详情',
    'business.businessName': '商家名称',
    'business.businessNamePlaceholder': '输入商家名称',
    'business.address': '地址',
    'business.addressPlaceholder': '输入完整地址',
    'business.phone': '电话号码',
    'business.phonePlaceholder': '(555) 123-4567',
    'business.website': '网站地址',
    'business.websitePlaceholder': 'https://www.example.com',
    'business.currentStats': '当前统计',
    'business.avgRating': '平均评分',
    'business.totalReviews': '总评价数',
    'business.openingHours': '营业时间',
    'business.enterHours': '每天的营业时间占一行',
    'business.addCategory': '添加',
    'business.noCategories': '暂无分类',
    'business.categoryPlaceholder': '输入分类名称',
    'business.saveChanges': '保存更改',
    'business.saving': '保存中...',
    'business.discard': '放弃',

    // Auth
    'auth.appName': '评价同步',
    'auth.appTagline': '管理您的 Google 商家评价',
    'auth.signIn': '登录',
    'auth.signUp': '注册',
    'auth.name': '姓名',
    'auth.namePlaceholder': '您的姓名',
    'auth.email': '邮箱',
    'auth.emailPlaceholder': 'you@example.com',
    'auth.password': '密码',
    'auth.passwordPlaceholder': '至少8个字符',
    'auth.submitSignIn': '登录',
    'auth.submitSignUp': '创建账号',
    'auth.orContinue': '或使用以下方式继续',
    'auth.google': 'Google',

    // Optimization
    'opt.loading': '加载中...',
    'opt.loadingTitle': '加载中...',
    'opt.initializing': '正在初始化优化引擎...',
    'opt.scanning': '正在扫描商家门店',
    'opt.analyzing': '正在分析评价模式',
    'opt.checkingCitations': '正在检查引用一致性',
    'opt.generatingRecs': '正在生成建议',
    'opt.analyzingAi': 'AI 正在分析您的商家资料',
    'opt.evaluating': '评估门店、评价、引用等...',
    'opt.startAnalysis': '开始分析',
    'opt.regenerate': '重新生成',
    'opt.analyzingWithAi': 'AI 分析中...',
    'opt.overview': '概览',
    'opt.insights': '优化建议',
    'opt.competitive': '竞争分析',
    'opt.quickWins': '快速见效',
    'opt.recommendations': '优化建议',
    'opt.competitorInsights': '竞争对手洞察',
    'opt.highPriority': '高优先级',
    'opt.all': '全部',
    'opt.high': '高',
    'opt.med': '中',
    'opt.low': '低',
    'opt.allGood': '一切正常！',
    'opt.noIssues': '当前筛选条件下没有问题。',
    'opt.aiGenerated': '基于您资料生成的AI优化建议',
    'opt.marketInsights': '市场洞察与战略机会',
    'opt.highImpactLowEffort': '高影响、低投入的优化行动',
    'opt.marketData': '暂无竞争数据',
    'opt.competitiveGenerated': '下次分析时将生成竞争对手洞察',
    'opt.noQuickWins': '暂无可用快速优化',
    'opt.quickWinsAppear': '发现优化机会后将显示快速优化建议',
    'opt.takeAction': '采取行动',
    'opt.recommendation': '建议',
    'opt.current': '当前',
    'opt.target': '目标',
    'opt.potentialImpact': '潜在影响',
    'opt.photos': '照片',
    'opt.reviews': '评价',
    'opt.description': '描述',
    'opt.hours': '营业时间',
    'opt.contact': '联系方式',
    'opt.verification': '信息验证',
    'opt.quickWinsSubtitle': '高影响、低投入的行动',
    'opt.viewAll': '查看全部',
    'opt.yourRank': '您的排名',
    'opt.notRanked': '未上榜',
    'opt.results': '条结果',
    'opt.actionSteps': '行动步骤',
    'opt.impact': '影响',
    'opt.searchMap': '搜索地图',
    'opt.top3': '前3名',
    'opt.top10': '前10名',
    'opt.pointsScanned': '已扫描点数',
    'opt.avgRank': '平均排名',
    'opt.seoHealthScore': 'SEO 健康评分',
    'opt.impactHigh': '高影响',
    'opt.impactMedium': '中影响',
    'opt.impactLow': '低影响',

    // Page Loader
    'app.loading': '加载中...',
    'app.loadingDesc': '正在准备所有内容',
    'listings.loading': '正在加载门店...',
    'listings.loadingDesc': '正在获取您的商家位置',
    'reviews.loading': '正在加载评价...',
    'reviews.loadingDesc': '正在收集客户反馈',
    'settings.loading': '正在加载设置...',
    'settings.loadingDesc': '正在获取您的偏好设置',
    'automations.loading': '正在加载自动化...',
    'automations.loadingDesc': '正在准备您的工作流',
    'realComment.loading': '加载中...',
    'realComment.loadingDesc': '正在设置智能回复',
    'rednote.checkingAccountStatus': '正在检查小红书账号状态',
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('app_language') as Language;
    if (savedLang && (savedLang === 'en' || savedLang === 'zh')) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
