import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.listings': 'Listings',
    'nav.reviews': 'Reviews',
    'nav.bulkEdits': 'Bulk Edits',
    'nav.editsLog': 'Edits Log',
    'nav.publishing': 'Publishing',
    'nav.reports': 'Reports',
    'nav.seo': 'SEO',
    'nav.comments': 'Comments',
    'nav.posts': 'Posts',
    'nav.docs': 'Documentation',
    'nav.settings': 'Settings',
    'nav.help': 'Help',
    'nav.connectBusiness': 'Connect Business',

    // Header
    'header.search': 'Search...',
    'header.locations': 'Locations',
    'header.keywords': 'Keywords',

    // Comments Gen
    'comments.title': 'Auto Comments',
    'comments.subtitle': 'Generate and schedule reviews using your managed Google accounts.',
    'comments.quota': 'Monthly Quota',
    'comments.remaining': 'remaining',
    'comments.setup': 'Task Setup',
    'comments.selectAccount': 'Select Account',
    'comments.targetLocation': 'Target Location (Optional)',
    'comments.generation': 'Content Generation',
    'comments.keywords': 'Keywords / Context',
    'comments.keywordsPlaceholder': 'e.g., great coffee, friendly staff, fast wifi',
    'comments.generateBtn': 'Generate',
    'comments.reviewContent': 'Review Content',
    'comments.reviewPlaceholder': 'Generated review will appear here. You can edit it before saving.',
    'comments.photos': 'Photos (Optional)',
    'comments.addPhoto': 'Add Photo',
    'comments.saveTask': 'Save Task to Queue',
    'comments.quotaExceeded': 'Monthly quota exceeded. Cannot save new tasks.',
    'comments.errorKeywords': 'Please enter keywords first.',
    'comments.errorAccount': 'Please select a Google account.',
    'comments.errorContent': 'Please generate or write comment content.',
    'comments.success': 'Comment task saved successfully! It is now pending execution.',

    // App
    'app.title.dashboard': 'Local SEO Manager',
    'app.title.listings': 'Listings & Profile',
    'app.title.reviews': 'Unified Inbox',
    'app.title.comments-gen': 'Auto Comments',
    'app.title.rank-tracker': 'Geo-Grid Rank Tracker',
    'app.title.posts': 'Content Calendar',
    'app.title.reports': 'Analytics & Reports',
    'app.title.keywords': 'Keyword Management',
    'app.title.settings': 'API Settings',
    'app.title.docs': 'Documentation',
    'app.configWarning': 'Please configure your API settings to use the application.',
    'app.goToSettings': 'Go to Settings',
    'dashboard.subtitle': 'Welcome back. Here\'s what\'s happening with your locations today.',
    'dashboard.totalLocations': 'Total Locations',
    'dashboard.avgRating': 'Avg Rating',
    'dashboard.totalReviews': 'Total Reviews',
    'dashboard.replyRate': 'Reply Rate',
    'dashboard.unreplied': 'Unreplied',
    'dashboard.replied': 'Replied',
    'dashboard.viewAll': 'View All',
    'dashboard.traffic': 'Traffic Trend',
    'dashboard.views': 'Views',
    'dashboard.clicks': 'Clicks',
    'dashboard.topKeywords': 'Top Keywords',
    'dashboard.keyword': 'Keyword',
    'dashboard.rank': 'Rank',
    'dashboard.volume': 'Volume',
    'dashboard.trend': 'Trend',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.activity.review': 'New 5-Star Review',
    'dashboard.activity.post': 'Auto-Post Success',
    'dashboard.activity.sync': 'Location data synced',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.action.reply': 'Reply to Reviews',
    'dashboard.action.post': 'Create Post',
    'dashboard.action.sync': 'Sync Data',
    'dashboard.locationFocus': 'Location Focus',
    'dashboard.heatmap': 'Local Visibility Heatmap',
    'dashboard.updated': 'Updated',
    'dashboard.aiSuggestion': 'AI Suggestion',
    'dashboard.aiSuggestionDesc': 'You have 12 unanswered questions on the Arlington profile. Respond now to boost engagement.',
    'dashboard.openAiAssistant': 'Open AI Assistant',
    'dashboard.health': 'Health',
    'dashboard.profileCompleteness': 'Profile Completeness',
    'dashboard.businessName': 'Business name',
    'dashboard.address': 'Address (Location)',
    'dashboard.website': 'Website URL',
    'dashboard.phoneNumber': 'Phone number',
    'dashboard.numberOfReviews': 'Number of reviews',
    'dashboard.per100': '/ 100',
    'dashboard.per5': '/ 5',
    'dashboard.reviewsUnit': 'reviews',
    'dashboard.performanceOverview': 'Performance overview across all your business locations',
    'dashboard.last7Days': 'Last 7 Days',
    'dashboard.last30Days': 'Last 30 Days',
    'dashboard.last90Days': 'Last 90 Days',
    'dashboard.last12Months': 'Last 12 Months',
    'dashboard.searchViews': 'Search Views',
    'dashboard.mapViews': 'Map Views',
    'dashboard.websiteClicks': 'Website Clicks',
    'dashboard.directionRequests': 'Direction Requests',
    'dashboard.phoneCalls': 'Phone Calls',
    'dashboard.publishedPosts': 'Published Posts',
    'dashboard.overviewImpressions': 'Overview: Impressions',
    'dashboard.impressionsDesc': 'Search views and map views over time',
    'dashboard.overviewActions': 'Overview: Actions',
    'dashboard.actionsDesc': 'Website clicks, directions, and calls over time',
    'dashboard.all': 'All',
    'dashboard.positive': 'Positive',
    'dashboard.negative': 'Negative',
    'dashboard.noReviewsYet': 'No reviews yet',
    'dashboard.reviewTrends': 'Review Trends',
    'dashboard.newReviewsVsResponses': 'New reviews vs responses over time',
    'dashboard.excellent': 'Excellent',
    'dashboard.good': 'Good',
    'dashboard.needsAttention': 'Needs Attention',
    'dashboard.poor': 'Poor',
    'dashboard.averPostingTime': 'Aver. Posting Time',
    'dashboard.averResponseTime': 'Aver. Response Time',
    'dashboard.responsePct': 'Response %',
    'dashboard.loadingData': 'Loading dashboard data...',
    'dashboard.selectPeriod': 'Select period',
    'dashboard.recentReviews': 'Recent Reviews',
    'dashboard.allLocations': 'All Locations',
    'dashboard.noDataAvailable': 'No data available',

    // Listings
    'listings.title': 'Locations & Profiles',
    'listings.subtitle': 'Manage your business information across all locations.',
    'listings.syncAll': 'Sync All',
    'listings.addLocation': 'Add Location',
    'listings.search': 'Search locations...',
    'listings.status.synced': 'Synced',
    'listings.status.pending': 'Pending',
    'listings.table.name': 'Name',
    'listings.table.address': 'Address',
    'listings.table.phone': 'Phone',
    'listings.table.status': 'Status',
    'listings.table.actions': 'Actions',
    'listings.edit': 'Edit',
    'listings.view': 'View',
    'listings.editor': 'Business Info Editor',
    'listings.noLocations': 'No Locations Found',
    'listings.noLocationsDesc': 'Connect your Google Business Profile and sync to view and edit your locations here.',
    'listings.connectGoogle': 'Connect Google Account',
    'listings.businessHours': 'Business Hours',
    'listings.days.monday': 'Monday',
    'listings.days.tuesday': 'Tuesday',
    'listings.days.wednesday': 'Wednesday',
    'listings.days.thursday': 'Thursday',
    'listings.days.friday': 'Friday',
    'listings.days.saturday': 'Saturday',
    'listings.days.sunday': 'Sunday',
    'listings.discard': 'Discard Changes',
    'listings.save': 'Save Profile',
    'listings.mapPresence': 'Map Presence',
    'listings.verifiedPosition': 'Verified Position',
    'listings.searchPerformance': 'Search Performance',
    'listings.directSearches': 'Direct Searches',
    'listings.discoverySearches': 'Discovery Searches',
    'listings.viewAnalytics': 'View Detailed Analytics',

    // Reviews
    'reviews.title': 'Unified Inbox',
    'reviews.subtitle': 'Manage and reply to customer reviews across all locations.',
    'reviews.filter.all': 'All Reviews',
    'reviews.filter.unreplied': 'Unreplied',
    'reviews.filter.replied': 'Replied',
    'reviews.search': 'Search reviews...',
    'reviews.replyBtn': 'Reply',
    'reviews.aiReplyBtn': 'AI Reply',
    'reviews.repliedBy': 'Replied by',
    'reviews.aiGenerated': 'AI Generated',
    'reviews.syncReviews': 'Sync reviews',
    'reviews.filter': 'Filter',
    'reviews.noReviews': 'No reviews found.',
    'reviews.noReviewsDesc': 'Click Sync reviews to import from Google.',
    'reviews.noComment': 'No comment provided.',
    'reviews.googleVerified': 'Google verified',
    'reviews.posted': 'Posted',
    'reviews.replied': 'Replied',
    'reviews.respondToReview': 'Respond to review',
    'reviews.replyPlaceholder': 'Write your reply…',
    'reviews.readyToSend': 'Ready to send',
    'reviews.sendReply': 'Send reply',
    'reviews.selectReview': 'Select a review to read details',
    'reviews.noReviewsAvailable': 'No reviews yet',
    'listings.placesApiKeyBanner': 'Google Places API key required. Add it at the top of Settings → Google Business Profile, or set GOOGLE_PLACES_API_KEY in .env.',
    'listings.placesApiKeyManualError': 'Configure the Google Places API key in Settings (Google Business Profile section at the top), or set GOOGLE_PLACES_API_KEY in .env.',

    // Settings
    'settings.title': 'API Settings',
    'settings.subtitle': 'Configure your API keys to connect your local business data. These keys are stored securely and are required to sync your listings and reviews.',
    'settings.googleApi': 'Google Business Profile API',
    'settings.googleClientId': 'Google Client ID',
    'settings.googleClientSecret': 'Google Client Secret',
    'settings.geminiApi': 'Google Gemini API',
    'settings.geminiApiKey': 'Gemini API Key',
    'settings.googlePlacesApiKey': 'Google Places API Key',
    'settings.googlePlacesSectionTitle': 'Google Places API',
    'settings.googlePlacesApiKeyDesc': 'Used to search and validate Google Business locations on the Listings page. Separate from OAuth (Business Profile sync).',
    'settings.googlePlacesApiKeyHint': 'Enable Places API in Google Cloud Console, then create an API key (restrict it to Places for production).',
    'settings.googleOAuthTitle': 'Google Business Profile (OAuth)',
    'settings.googleOAuthDesc': 'Required to sync reviews from Google and post replies. Separate from the Places API key above. Link each store to Google in Listings using Place ID.',
    'settings.saveBtn': 'Save Configuration',
    'settings.saving': 'Saving...',
    'settings.success': 'Settings saved successfully.',
    'settings.error': 'Failed to save settings.',
    'settings.teamMembers': 'Team Members',
    'settings.teamMembersDesc': 'Manage who has access to your business dashboard.',
    'settings.enterEmail': 'Enter email address',
    'settings.addMember': 'Add Member',
    'settings.noMembers': 'No team members added yet.',
    'settings.added': 'Added',
    'settings.removeMember': 'Remove member',

    // Reports
    'reports.title': 'GBP Performance Report',
    'reports.subtitle': 'Visualize search visibility, map interactions, and customer actions for your business listings.',
    'reports.source': 'Source',
    'reports.allLocations': 'All Locations',
    'reports.startDate': 'Start Date',
    'reports.endDate': 'End Date',
    'reports.downloadPdf': 'Download PDF Report',
    'reports.generating': 'Generating...',
    'reports.loading': 'Loading report data...',
    'reports.noData': 'No data available',
    'reports.noDataHint': 'Make sure your Google Business Profile is connected and has activity in this date range.',
    'reports.totalSearchViews': 'Total Search Views',
    'reports.totalMapViews': 'Total Map Views',
    'reports.totalActions': 'Total Actions',
    'reports.phoneCalls': 'Phone Calls',
    'reports.vsPrevPeriod': '% vs previous period',
    'reports.searchPerf': 'Search Performance',
    'reports.trendOverTime': 'Trend Over Time',
    'reports.monthlyBreakdown': 'Monthly Breakdown',
    'reports.period': 'Period',
    'reports.search': 'Search',
    'reports.maps': 'Maps',
    'reports.chg': '% Chg',
    'reports.total': 'Total',
    'reports.searchVsMapShare': 'Search vs Map Share',
    'reports.weeklySearch': 'Weekly Search Performance',
    'reports.actionsPerf': 'Actions Performance',
    'reports.directions': 'Directions',
    'reports.calls': 'Calls',
    'reports.actionsBreakdown': 'Actions Breakdown',
    'reports.weeklyActions': 'Weekly Actions',
    'reports.avgRank': 'Average Rank',
    'reports.across': 'across',
    'reports.points': 'points',
    'reports.top3Positions': 'Top 3 Positions',
    'reports.top10Positions': 'Top 10 Positions',
    'reports.ofAllPoints': 'of all grid points',
    'reports.pointsScanned': 'Points Scanned',
    'reports.gridPoints': 'grid points',
    'reports.searchGridMap': 'Search Grid Map',
    'reports.keyword': 'Keyword',
    'reports.gridPointsAround': 'grid points around',
    'reports.rank1to3': 'Rank 1-3',
    'reports.rank4to10': 'Rank 4-10',
    'reports.rank11plus': 'Rank 11+',
    'reports.noData2': 'No data',
    'reports.results': 'results',
    'reports.notFound': 'Not found',
    'reports.yourRankHere': 'Your rank here',
    'reports.totalResults': 'Total results',
    'reports.coordinates': 'Coordinates',
    'reports.competitorsVisible': 'Competitors visible',
    'reports.topCompetitors': 'Top Competitors at This Point',
    'reports.noCompetitorData': 'No competitor data for this point.',
    'reports.allGridPoints': 'All Grid Points',
    'reports.point': 'Point',
    'reports.yourRank': 'Your Rank',
    'reports.results2': 'Results',
    'reports.topCompetitor': 'Top Competitor',
    'reports.notRanked': 'Not ranked',
    'reports.reviews': 'reviews',
    'reports.localSearchGrid': 'Local Search Grid',
    'reports.localSearchGridDesc': 'Visualize rankings on a geographical map to identify local opportunities and track competitor performance.',
    'reports.createReport': 'Create report',
    'reports.keywordQuery': 'Keyword / Query',
    'reports.keywordPlaceholder': 'e.g. "mini bowl" or "restaurant near me"',
    'reports.scanning': 'Scanning...',
    'reports.noCoords': 'No location coordinates found. Please connect a Google Business Profile listing with coordinates.',
    'reports.rankingCompetitors': 'Ranking competitors',
    'reports.rankingCompetitorsDesc': 'Top-performing search competitors, based on the Grid Points for this keyword',
    'reports.noDataYet': 'No data available yet. Create your first report to start tracking your local ranking performance against competitors.',
    'reports.seoOptimization': 'SEO optimization:',
    'reports.reportSettings': 'Report settings',
    'reports.generateOptReport': 'Generate an optimization report. Get a guide on how to increase your ranking on Google and much more.',
    'reports.periodLastWeek': 'Period: Last week',
    'reports.periodLastMonth': 'Period: Last month',
    'reports.periodLast3Months': 'Period: Last 3 months',
    'reports.generateReport': 'Generate report',
    'reports.credits': 'credits',
    'reports.gridPointDetails': 'Grid Point',
    'reports.you': 'You',
    'reports.downloadFailed': 'PDF download failed',

    // SEO
    'seo.localSearchGrid': 'Local search grid',
    'seo.localCitations': 'Local citations',
    'seo.optimization': 'Optimization',
    'seo.loading': 'Loading SEO data...',
    'seo.keywords': 'Keywords',
    'seo.localCitation': 'Local citation:',
    'seo.baselineInfo': 'Baseline information (Google)',
    'seo.businessHours': 'Business Hours',
    'seo.name': 'Name',
    'seo.status': 'Status',
    'seo.address': 'Address',
    'seo.hours': 'Hours',
    'seo.phone': 'Phone',
    'seo.lastUpdate': 'Last update:',
    'seo.notYourBusiness': 'Not your business?',
    'seo.matched': 'Matched',
    'seo.mismatch': 'Mismatch',

    // Bulk Edits
    'bulkEdits.title': 'Bulk Edits',
    'bulkEdits.subtitle': 'Update multiple business locations simultaneously.',
    'bulkEdits.refresh': 'Refresh',
    'bulkEdits.updateResults': 'Update Results',
    'bulkEdits.updatedSuccess': 'updated successfully',
    'bulkEdits.failed': 'failed',
    'bulkEdits.done': 'Done',
    'bulkEdits.selectLocations': 'Select locations',
    'bulkEdits.noListings': 'No listings found. Make sure EmbedSocial is configured.',
    'bulkEdits.selectAll': 'Select all listings',
    'bulkEdits.deselectAll': 'Deselect All',
    'bulkEdits.selectAll2': 'Select All',
    'bulkEdits.noAddress': 'No address',
    'bulkEdits.chooseFields': 'Choose fields to edit',
    'bulkEdits.enterValues': 'Enter the new values for the fields you want to update...',
    'bulkEdits.nextChooseFields': 'Next: Choose Fields',
    'bulkEdits.back': 'Back',
    'bulkEdits.reviewChanges': 'Review Changes',
    'bulkEdits.completeStep1': 'Complete Step 1 to select fields.',
    'bulkEdits.reviewApply': 'Review & Apply',
    'bulkEdits.summary': 'Summary',
    'bulkEdits.locationsSelected': 'Locations selected:',
    'bulkEdits.fieldsToUpdate': 'Fields to update:',
    'bulkEdits.changes': 'Changes',
    'bulkEdits.applyChanges': 'Apply Changes',
    'bulkEdits.saving': 'Saving...',
    'bulkEdits.completePrevSteps': 'Complete previous steps to review changes.',

    // Edits Log
    'editsLog.title': 'Activity Log',
    'editsLog.subtitle': 'Track all changes and sync activities',
    'editsLog.allActivity': 'All Activity',
    'editsLog.created': 'Created',
    'editsLog.posts': 'Posts',
    'editsLog.replies': 'Replies',
    'editsLog.sync': 'Sync',
    'editsLog.deleted': 'Deleted',
    'editsLog.justNow': 'Just now',
    'editsLog.minsAgo': 'm ago',
    'editsLog.hoursAgo': 'h ago',
    'editsLog.daysAgo': 'd ago',
    'editsLog.noActivity': 'No Activity Yet',
    'editsLog.noActivityDesc': 'Connect listings, send review replies, and create posts to see your activity here.',

    // Publishing
    'publishing.createNewPost': 'Create New Post',
    'publishing.content': 'Content',
    'publishing.contentPlaceholder': 'What would you like to share?',
    'publishing.scheduleOptional': 'Schedule (optional)',
    'publishing.selectLocation': 'Select a location',
    'publishing.cancel': 'Cancel',
    'publishing.creating': 'Creating...',
    'publishing.schedulePost': 'Schedule Post',
    'publishing.saveDraft': 'Save as Draft',
    'publishing.today': 'Today',
    'publishing.published': 'published',
    'publishing.scheduled': 'scheduled',
    'publishing.drafts': 'drafts',
    'publishing.allLocations': 'All Locations',
    'publishing.statusAll': 'Status: All',
    'publishing.published2': 'Published',
    'publishing.scheduled2': 'Scheduled',
    'publishing.draft': 'Draft',
    'publishing.publishNow': 'Publish now',
    'publishing.deletePost': 'Delete post',
    'publishing.scheduledStatus': 'Scheduled',
    'publishing.draftStatus': 'Saved as draft',

    // Help
    'help.helpCenter': 'Help Center',
    'help.helpSubtitle': 'Learn how to set up and use Review Sync App',
    'help.features': 'Features',
    'help.quickSetup': 'Quick Setup Guide',
    'help.faq': 'Frequently Asked Questions',
    'help.feature1': 'Review Management',
    'help.feature1Desc': 'View and manage Google reviews across all locations from one unified inbox.',
    'help.feature2': 'AI-Powered Replies',
    'help.feature2Desc': 'Generate professional responses to customer reviews with a single click.',
    'help.feature3': 'Smart Sync',
    'help.feature3Desc': 'Automatically sync your business listings and review data on a schedule.',
    'help.feature4': 'Publishing',
    'help.feature4Desc': 'Schedule and manage posts to Google Business Profiles.',
    'help.step1': 'Step 1: Connect Your Listings',
    'help.step1Desc': 'Go to Settings > Google Business Listings and click Connect New Listing.',
    'help.step2': 'Step 2: Manage Reviews',
    'help.step2Desc': 'Visit the Reviews tab to view and respond to customer feedback.',
    'help.step3': 'Step 3: Set Up AI Replies',
    'help.step3Desc': 'Configure your Gemini API key in Settings to enable AI reply generation.',
    'help.step4': 'Step 4: Edit Listings',
    'help.step4Desc': 'Edit business information across all locations using Listings or Bulk Edits.',
    'help.faq1': 'How do I get started?',
    'help.faq1Ans': 'Sign in with your Google account, then go to Settings > Google Business Listings to connect your locations.',
    'help.faq2': 'How do I connect my business listings?',
    'help.faq2Ans': 'Go to Settings > Google Business Listings and click Connect New Listing. Follow the Google OAuth flow.',
    'help.faq3': 'Why are my reviews not showing?',
    'help.faq3Ans': 'Make sure you have connected your listings via Google OAuth in Settings. Reviews are synced from Google.',
    'help.faq4': 'How does AI reply generation work?',
    'help.faq4Ans': 'The app uses Gemini AI to generate professional replies based on the review content. Configure your API key in Settings.',
    'help.faq5': 'Can I bulk edit multiple locations?',
    'help.faq5Ans': 'Yes! Go to Bulk Edits, select multiple locations, choose the fields to update, and apply changes.',
    'help.faq6': 'How do I publish posts to Google?',
    'help.faq6Ans': 'Go to Publishing and click Create New Post. Select a location and schedule or publish immediately.',

    // Edit Business Page
    'business.editInfo': 'Edit Business Info',
    'business.updateInfo': 'Update your listing information',
    'business.basicInfo': 'Basic Info',
    'business.hours': 'Hours',
    'business.categories': 'Categories',
    'business.businessDetails': 'Business Details',
    'business.businessName': 'Business Name',
    'business.businessNamePlaceholder': 'Enter business name',
    'business.address': 'Address',
    'business.addressPlaceholder': 'Enter full address',
    'business.phone': 'Phone Number',
    'business.phonePlaceholder': '(555) 123-4567',
    'business.website': 'Website URL',
    'business.websitePlaceholder': 'https://www.example.com',
    'business.currentStats': 'Current Stats',
    'business.avgRating': 'Average Rating',
    'business.totalReviews': 'Total Reviews',
    'business.openingHours': 'Opening Hours',
    'business.enterHours': 'Enter each day\'s hours on a new line',
    'business.addCategory': 'Add',
    'business.noCategories': 'No categories added yet',
    'business.categoryPlaceholder': 'Enter category name',
    'business.saveChanges': 'Save Changes',
    'business.saving': 'Saving...',
    'business.discard': 'Discard',

    // Auth
    'auth.appName': 'Review Sync',
    'auth.appTagline': 'Manage your Google Business reviews',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.name': 'Name',
    'auth.namePlaceholder': 'Your name',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'you@example.com',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Min. 8 characters',
    'auth.submitSignIn': 'Sign In',
    'auth.submitSignUp': 'Create Account',
    'auth.orContinue': 'or continue with',
    'auth.google': 'Google',

    // App errors
    'app.errorBoundary': 'Something went wrong.',
    'app.tryAgain': 'Try again',
    'app.loading': 'Loading...',
  },
  zh: {
    // Navigation
    'nav.dashboard': '仪表盘',
    'nav.listings': '门店管理',
    'nav.reviews': '评价管理',
    'nav.bulkEdits': '批量编辑',
    'nav.editsLog': '编辑日志',
    'nav.publishing': '内容发布',
    'nav.reports': '数据报告',
    'nav.seo': 'SEO优化',
    'nav.comments': '评论',
    'nav.posts': '贴文管理',
    'nav.docs': '使用文档',
    'nav.settings': '系统设置',
    'nav.help': '帮助中心',
    'nav.connectBusiness': '连接商家',

    // Header
    'header.search': '搜索...',
    'header.locations': '门店',
    'header.keywords': '关键词',

    // Comments Gen
    'comments.title': '自动评价',
    'comments.subtitle': '使用您管理的 Google 账号生成并定时发布评价。',
    'comments.quota': '本月额度',
    'comments.remaining': '剩余',
    'comments.setup': '任务设置',
    'comments.selectAccount': '选择账号',
    'comments.targetLocation': '目标门店（可选）',
    'comments.generation': '内容生成',
    'comments.keywords': '关键词 / 上下文',
    'comments.keywordsPlaceholder': '例如：咖啡好喝，服务热情，环境安静',
    'comments.generateBtn': '生成评价',
    'comments.reviewContent': '评价内容',
    'comments.reviewPlaceholder': '生成的评价会显示在这里。您可以在保存前进行修改。',
    'comments.photos': '上传图片（可选）',
    'comments.addPhoto': '添加图片',
    'comments.saveTask': '保存任务到队列',
    'comments.quotaExceeded': '本月额度已用完，无法保存新任务。',
    'comments.errorKeywords': '请先输入关键词。',
    'comments.errorAccount': '请选择一个 Google 账号。',
    'comments.errorContent': '请生成或手动输入评价内容。',
    'comments.success': '评价任务保存成功！已加入执行队列。',

    // App
    'app.title.dashboard': '本地 SEO 管理器',
    'app.title.listings': '门店与资料',
    'app.title.reviews': '统一收件箱',
    'app.title.comments-gen': '自动评价',
    'app.title.rank-tracker': '排名追踪',
    'app.title.posts': '贴文管理',
    'app.title.reports': '数据报告',
    'app.title.keywords': '关键词管理',
    'app.title.settings': 'API 设置',
    'app.title.docs': '使用文档',
    'app.configWarning': '请配置您的 API 设置以使用该应用程序。',
    'app.goToSettings': '前往设置',
    'dashboard.subtitle': '欢迎回来。以下是您门店今天的最新动态。',
    'dashboard.totalLocations': '总门店数',
    'dashboard.avgRating': '平均评分',
    'dashboard.totalReviews': '总评价数',
    'dashboard.replyRate': '回复率',
    'dashboard.unreplied': '未回复',
    'dashboard.replied': '已回复',
    'dashboard.viewAll': '查看全部',
    'dashboard.traffic': '流量趋势',
    'dashboard.views': '浏览量',
    'dashboard.clicks': '点击量',
    'dashboard.topKeywords': '热门关键词',
    'dashboard.keyword': '关键词',
    'dashboard.rank': '排名',
    'dashboard.volume': '搜索量',
    'dashboard.trend': '趋势',
    'dashboard.recentActivity': '近期动态',
    'dashboard.activity.review': '收到新的 5 星评价',
    'dashboard.activity.post': '贴文自动发布成功',
    'dashboard.activity.sync': '门店数据同步完成',
    'dashboard.quickActions': '快捷操作',
    'dashboard.action.reply': '回复评价',
    'dashboard.action.post': '创建贴文',
    'dashboard.action.sync': '同步数据',
    'dashboard.locationFocus': '重点门店',
    'dashboard.heatmap': '本地可见度热力图',
    'dashboard.updated': '更新于',
    'dashboard.aiSuggestion': 'AI 建议',
    'dashboard.aiSuggestionDesc': 'Arlington 门店有 12 个未回复的问题。立即回复以提升互动率。',
    'dashboard.openAiAssistant': '打开 AI 助手',
    'dashboard.health': '健康度',
    'dashboard.profileCompleteness': '资料完整度',
    'dashboard.businessName': '商家名称',
    'dashboard.address': '地址（位置）',
    'dashboard.website': '网站地址',
    'dashboard.phoneNumber': '电话号码',
    'dashboard.numberOfReviews': '评价数量',
    'dashboard.per100': '/ 100',
    'dashboard.per5': '/ 5',
    'dashboard.reviewsUnit': '条评价',
    'dashboard.performanceOverview': '所有商家门店的表现概览',
    'dashboard.last7Days': '最近7天',
    'dashboard.last30Days': '最近30天',
    'dashboard.last90Days': '最近90天',
    'dashboard.last12Months': '最近12个月',
    'dashboard.searchViews': '搜索展示',
    'dashboard.mapViews': '地图展示',
    'dashboard.websiteClicks': '网站点击',
    'dashboard.directionRequests': '导航请求',
    'dashboard.phoneCalls': '电话拨打',
    'dashboard.publishedPosts': '已发布贴文',
    'dashboard.overviewImpressions': '概览：展示',
    'dashboard.impressionsDesc': '搜索展示和地图展示的时间趋势',
    'dashboard.overviewActions': '概览：互动',
    'dashboard.actionsDesc': '网站点击、导航请求和电话拨打的时间趋势',
    'dashboard.all': '全部',
    'dashboard.positive': '正面',
    'dashboard.negative': '负面',
    'dashboard.noReviewsYet': '暂无评价',
    'dashboard.reviewTrends': '评价趋势',
    'dashboard.newReviewsVsResponses': '新增评价与回复的时间趋势',
    'dashboard.excellent': '优秀',
    'dashboard.good': '良好',
    'dashboard.needsAttention': '需要关注',
    'dashboard.poor': '较差',
    'dashboard.averPostingTime': '平均发帖时间',
    'dashboard.averResponseTime': '平均回复时间',
    'dashboard.responsePct': '回复率',
    'dashboard.loadingData': '正在加载仪表盘数据...',
    'dashboard.selectPeriod': '选择周期',
    'dashboard.recentReviews': '近期评价',
    'dashboard.allLocations': '全部门店',
    'dashboard.noDataAvailable': '暂无数据',

    // Listings
    'listings.title': '门店与资料',
    'listings.subtitle': '管理您所有门店的商业信息。',
    'listings.syncAll': '全部同步',
    'listings.addLocation': '添加门店',
    'listings.search': '搜索门店...',
    'listings.status.synced': '已同步',
    'listings.status.pending': '待同步',
    'listings.table.name': '名称',
    'listings.table.address': '地址',
    'listings.table.phone': '电话',
    'listings.table.status': '状态',
    'listings.table.actions': '操作',
    'listings.edit': '编辑',
    'listings.view': '查看',
    'listings.editor': '商家信息编辑器',
    'listings.noLocations': '未找到门店',
    'listings.noLocationsDesc': '连接您的 Google 商家资料并同步，即可在此处查看和编辑您的门店。',
    'listings.connectGoogle': '连接 Google 账号',
    'listings.businessHours': '营业时间',
    'listings.days.monday': '星期一',
    'listings.days.tuesday': '星期二',
    'listings.days.wednesday': '星期三',
    'listings.days.thursday': '星期四',
    'listings.days.friday': '星期五',
    'listings.days.saturday': '星期六',
    'listings.days.sunday': '星期日',
    'listings.discard': '放弃更改',
    'listings.save': '保存资料',
    'listings.mapPresence': '地图展示',
    'listings.verifiedPosition': '已验证位置',
    'listings.searchPerformance': '搜索表现',
    'listings.directSearches': '直接搜索',
    'listings.discoverySearches': '发现搜索',
    'listings.viewAnalytics': '查看详细分析',

    // Reviews
    'reviews.title': '统一收件箱',
    'reviews.subtitle': '管理并回复所有门店的客户评价。',
    'reviews.filter.all': '全部评价',
    'reviews.filter.unreplied': '未回复',
    'reviews.filter.replied': '已回复',
    'reviews.search': '搜索评价...',
    'reviews.replyBtn': '回复',
    'reviews.aiReplyBtn': 'AI 智能回复',
    'reviews.repliedBy': '回复人',
    'reviews.aiGenerated': 'AI 生成',
    'reviews.syncReviews': '同步评价',
    'reviews.filter': '筛选',
    'reviews.noReviews': '未找到评价。',
    'reviews.noReviewsDesc': '点击"同步评价"从 Google 获取。',
    'reviews.noComment': '未提供评论。',
    'reviews.googleVerified': 'Google 验证评价',
    'reviews.posted': '发布于',
    'reviews.replied': '已回复',
    'reviews.respondToReview': '回复评价',
    'reviews.replyPlaceholder': '写下您的个性化回复...',
    'reviews.readyToSend': '准备发送',
    'reviews.sendReply': '发送回复',
    'reviews.selectReview': '选择一条评价以查看详情',
    'reviews.noReviewsAvailable': '暂无评价',
    'listings.placesApiKeyBanner': '需要 Google Places API 密钥。请在"系统设置 → Google 商家资料"区块顶部填写，或在 .env 中设置 GOOGLE_PLACES_API_KEY。',
    'listings.placesApiKeyManualError': '请在"系统设置 → Google 商家资料"区块顶部填写 Google Places API 密钥，或在 .env 中设置 GOOGLE_PLACES_API_KEY。',

    // Settings
    'settings.title': 'API 设置',
    'settings.subtitle': '配置您的 API 密钥以连接本地业务数据。这些密钥将被安全存储，并用于同步您的门店和评价。',
    'settings.googleApi': 'Google 商家资料 API',
    'settings.googleClientId': 'Google 客户端 ID',
    'settings.googleClientSecret': 'Google 客户端密钥',
    'settings.geminiApi': 'Google Gemini API',
    'settings.geminiApiKey': 'Gemini API 密钥',
    'settings.googlePlacesApiKey': 'Google Places API 密钥',
    'settings.googlePlacesSectionTitle': 'Google Places API',
    'settings.googlePlacesApiKeyDesc': '用于在"门店管理"中搜索并校验 Google 商家地点。与下方 OAuth（商家资料同步）是两套配置。',
    'settings.googlePlacesApiKeyHint': '在 Google Cloud 控制台启用 Places API，再创建 API 密钥（生产环境建议限制为仅 Places）。',
    'settings.googleOAuthTitle': 'Google 商家资料（OAuth 登录）',
    'settings.googleOAuthDesc': '用于从 Google 同步评价并发布回复，与上方的 Places API 密钥不同。在"门店管理"里用 Place ID 关联门店后即可同步。',
    'settings.saveBtn': '保存配置',
    'settings.saving': '保存中...',
    'settings.success': '设置保存成功。',
    'settings.error': '保存设置失败。',
    'settings.teamMembers': '团队成员',
    'settings.teamMembersDesc': '管理谁可以访问您的业务仪表盘。',
    'settings.enterEmail': '输入邮箱地址',
    'settings.addMember': '添加成员',
    'settings.noMembers': '暂无团队成员。',
    'settings.added': '添加于',
    'settings.removeMember': '移除成员',

    // Reports
    'reports.title': 'GBP 业绩报告',
    'reports.subtitle': '可视化您的商家资料的搜索可见度、地图互动和客户行为数据。',
    'reports.source': '来源',
    'reports.allLocations': '全部门店',
    'reports.startDate': '开始日期',
    'reports.endDate': '结束日期',
    'reports.downloadPdf': '下载 PDF 报告',
    'reports.generating': '生成中...',
    'reports.loading': '正在加载报告数据...',
    'reports.noData': '暂无数据',
    'reports.noDataHint': '请确认已连接 Google 商家资料，且在所选日期范围内有相关活动。',
    'reports.totalSearchViews': '搜索展示总次数',
    'reports.totalMapViews': '地图展示总次数',
    'reports.totalActions': '互动总次数',
    'reports.phoneCalls': '电话拨打',
    'reports.vsPrevPeriod': '较上期变化',
    'reports.searchPerf': '搜索表现',
    'reports.trendOverTime': '时间趋势',
    'reports.monthlyBreakdown': '月度明细',
    'reports.period': '周期',
    'reports.search': '搜索',
    'reports.maps': '地图',
    'reports.chg': '变化',
    'reports.total': '合计',
    'reports.searchVsMapShare': '搜索与地图占比',
    'reports.weeklySearch': '每周搜索表现',
    'reports.actionsPerf': '互动表现',
    'reports.directions': '导航请求',
    'reports.calls': '电话',
    'reports.actionsBreakdown': '互动分类',
    'reports.weeklyActions': '每周互动',
    'reports.avgRank': '平均排名',
    'reports.across': '共',
    'reports.points': '个点',
    'reports.top3Positions': '前3名占比',
    'reports.top10Positions': '前10名占比',
    'reports.ofAllPoints': '所有网格点',
    'reports.pointsScanned': '已扫描点数',
    'reports.gridPoints': '个网格点',
    'reports.searchGridMap': '搜索网格地图',
    'reports.keyword': '关键词',
    'reports.gridPointsAround': '个网格点，环绕',
    'reports.rank1to3': '排名 1-3',
    'reports.rank4to10': '排名 4-10',
    'reports.rank11plus': '排名 11+',
    'reports.noData2': '暂无数据',
    'reports.results': '条结果',
    'reports.notFound': '未找到',
    'reports.yourRankHere': '此处您的排名',
    'reports.totalResults': '总结果数',
    'reports.coordinates': '坐标',
    'reports.competitorsVisible': '可见竞品数',
    'reports.topCompetitors': '此点前5竞品',
    'reports.noCompetitorData': '此点暂无竞品数据。',
    'reports.allGridPoints': '全部网格点',
    'reports.point': '网格点',
    'reports.yourRank': '您的排名',
    'reports.results2': '结果数',
    'reports.topCompetitor': '头部竞品',
    'reports.notRanked': '未上榜',
    'reports.reviews': '条评价',
    'reports.localSearchGrid': '本地搜索网格',
    'reports.localSearchGridDesc': '在地理地图上可视化排名，识别本地机会并追踪竞争对手表现。',
    'reports.createReport': '生成报告',
    'reports.keywordQuery': '关键词 / 搜索词',
    'reports.keywordPlaceholder': '例如："小碗菜" 或 "附近的餐厅"',
    'reports.scanning': '扫描中...',
    'reports.noCoords': '未找到位置坐标。请连接带有坐标的 Google 商家资料。',
    'reports.rankingCompetitors': '排名竞品',
    'reports.rankingCompetitorsDesc': '基于该关键词网格点，表现最佳的搜索竞争对手',
    'reports.noDataYet': '暂无数据。生成您的第一份报告，开始追踪本地排名表现与竞争对手。',
    'reports.seoOptimization': 'SEO 优化：',
    'reports.reportSettings': '报告设置',
    'reports.generateOptReport': '生成优化报告，获得提升 Google 排名等详细指南。',
    'reports.periodLastWeek': '周期：最近一周',
    'reports.periodLastMonth': '周期：最近一月',
    'reports.periodLast3Months': '周期：最近三月',
    'reports.generateReport': '生成报告',
    'reports.credits': '积分',
    'reports.gridPointDetails': '网格点详情',
    'reports.you': '您',
    'reports.downloadFailed': 'PDF 下载失败',

    // SEO
    'seo.localSearchGrid': '本地搜索网格',
    'seo.localCitations': '本地引用',
    'seo.optimization': '优化',
    'seo.loading': '正在加载 SEO 数据...',
    'seo.keywords': '关键词',
    'seo.localCitation': '本地引用：',
    'seo.baselineInfo': '基准信息（Google）',
    'seo.businessHours': '营业时间',
    'seo.name': '名称',
    'seo.status': '状态',
    'seo.address': '地址',
    'seo.hours': '时间',
    'seo.phone': '电话',
    'seo.lastUpdate': '最后更新：',
    'seo.notYourBusiness': '这不是您的商家？',
    'seo.matched': '匹配',
    'seo.mismatch': '不匹配',

    // Bulk Edits
    'bulkEdits.title': '批量编辑',
    'bulkEdits.subtitle': '同时更新多个商家门店。',
    'bulkEdits.refresh': '刷新',
    'bulkEdits.updateResults': '更新结果',
    'bulkEdits.updatedSuccess': '条更新成功',
    'bulkEdits.failed': '条失败',
    'bulkEdits.done': '完成',
    'bulkEdits.selectLocations': '选择门店',
    'bulkEdits.noListings': '未找到门店。请确认 EmbedSocial 已配置。',
    'bulkEdits.selectAll': '全选门店',
    'bulkEdits.deselectAll': '取消全选',
    'bulkEdits.selectAll2': '全选',
    'bulkEdits.noAddress': '无地址',
    'bulkEdits.chooseFields': '选择要编辑的字段',
    'bulkEdits.enterValues': '输入您要更新的字段值...',
    'bulkEdits.nextChooseFields': '下一步：选择字段',
    'bulkEdits.back': '上一步',
    'bulkEdits.reviewChanges': '审核变更',
    'bulkEdits.completeStep1': '请先完成步骤1以选择门店。',
    'bulkEdits.reviewApply': '审核并应用',
    'bulkEdits.summary': '摘要',
    'bulkEdits.locationsSelected': '已选门店：',
    'bulkEdits.fieldsToUpdate': '待更新字段：',
    'bulkEdits.changes': '变更',
    'bulkEdits.applyChanges': '应用变更',
    'bulkEdits.saving': '保存中...',
    'bulkEdits.completePrevSteps': '请完成前面的步骤以审核变更。',

    // Edits Log
    'editsLog.title': '操作日志',
    'editsLog.subtitle': '追踪所有变更和同步活动',
    'editsLog.allActivity': '全部活动',
    'editsLog.created': '创建',
    'editsLog.posts': '贴文',
    'editsLog.replies': '回复',
    'editsLog.sync': '同步',
    'editsLog.deleted': '已删除',
    'editsLog.justNow': '刚刚',
    'editsLog.minsAgo': '分钟前',
    'editsLog.hoursAgo': '小时前',
    'editsLog.daysAgo': '天前',
    'editsLog.noActivity': '暂无活动',
    'editsLog.noActivityDesc': '连接门店、发送评价回复和创建贴文后，即可在此处查看您的活动记录。',

    // Publishing
    'publishing.createNewPost': '创建新贴文',
    'publishing.content': '内容',
    'publishing.contentPlaceholder': '分享您想发布的内容？',
    'publishing.scheduleOptional': '定时发布（可选）',
    'publishing.selectLocation': '选择门店',
    'publishing.cancel': '取消',
    'publishing.creating': '创建中...',
    'publishing.schedulePost': '定时发布',
    'publishing.saveDraft': '保存草稿',
    'publishing.today': '今天',
    'publishing.published': '已发布',
    'publishing.scheduled': '待发布',
    'publishing.drafts': '草稿',
    'publishing.allLocations': '全部门店',
    'publishing.statusAll': '状态：全部',
    'publishing.published2': '已发布',
    'publishing.scheduled2': '待发布',
    'publishing.draft': '草稿',
    'publishing.publishNow': '立即发布',
    'publishing.deletePost': '删除贴文',
    'publishing.scheduledStatus': '已定时',
    'publishing.draftStatus': '已存为草稿',

    // Help
    'help.helpCenter': '帮助中心',
    'help.helpSubtitle': '了解如何设置和使用评价同步应用',
    'help.features': '功能介绍',
    'help.quickSetup': '快速设置指南',
    'help.faq': '常见问题',
    'help.feature1': '评价管理',
    'help.feature1Desc': '通过统一收件箱查看和管理所有门店的 Google 评价。',
    'help.feature2': 'AI 智能回复',
    'help.feature2Desc': '一键生成针对客户评价的专业回复。',
    'help.feature3': '智能同步',
    'help.feature3Desc': '按计划自动同步商家门店和评价数据。',
    'help.feature4': '内容发布',
    'help.feature4Desc': '定时发布和管理 Google 商家资料贴文。',
    'help.step1': '步骤1：连接您的门店',
    'help.step1Desc': '前往"系统设置 > Google 商家资料"，点击"连接新门店"。',
    'help.step2': '步骤2：管理评价',
    'help.step2Desc': '访问"评价管理"标签页，查看并回复客户反馈。',
    'help.step3': '步骤3：设置 AI 回复',
    'help.step3Desc': '在"系统设置"中配置 Gemini API 密钥以启用 AI 回复生成。',
    'help.step4': '步骤4：编辑门店',
    'help.step4Desc': '使用"门店管理"或"批量编辑"编辑所有门店的商家信息。',
    'help.faq1': '如何开始使用？',
    'help.faq1Ans': '使用 Google 账号登录，然后前往"系统设置 > Google 商家资料"连接您的门店。',
    'help.faq2': '如何连接我的商家门店？',
    'help.faq2Ans': '前往"系统设置 > Google 商家资料"，点击"连接新门店"，按提示完成 Google OAuth 授权。',
    'help.faq3': '为什么我的评价没有显示？',
    'help.faq3Ans': '请确认已在"系统设置"中通过 Google OAuth 连接了门店。评价数据从 Google 同步而来。',
    'help.faq4': 'AI 回复生成是如何工作的？',
    'help.faq4Ans': '应用使用 Gemini AI 根据评价内容生成专业回复。请在"系统设置"中配置您的 API 密钥。',
    'help.faq5': '我可以批量编辑多个门店吗？',
    'help.faq5Ans': '可以！前往"批量编辑"，选择多个门店，选择要更新的字段，然后应用变更。',
    'help.faq6': '如何向 Google 发布贴文？',
    'help.faq6Ans': '前往"内容发布"，点击"创建新贴文"，选择门店并设置发布时间或立即发布。',

    // Edit Business Page
    'business.editInfo': '编辑商家信息',
    'business.updateInfo': '更新您的门店资料',
    'business.basicInfo': '基本信息',
    'business.hours': '营业时间',
    'business.categories': '分类',
    'business.businessDetails': '商家详情',
    'business.businessName': '商家名称',
    'business.businessNamePlaceholder': '输入商家名称',
    'business.address': '地址',
    'business.addressPlaceholder': '输入完整地址',
    'business.phone': '电话号码',
    'business.phonePlaceholder': '(555) 123-4567',
    'business.website': '网站地址',
    'business.websitePlaceholder': 'https://www.example.com',
    'business.currentStats': '当前统计',
    'business.avgRating': '平均评分',
    'business.totalReviews': '总评价数',
    'business.openingHours': '营业时间',
    'business.enterHours': '每天的营业时间占一行',
    'business.addCategory': '添加',
    'business.noCategories': '暂无分类',
    'business.categoryPlaceholder': '输入分类名称',
    'business.saveChanges': '保存更改',
    'business.saving': '保存中...',
    'business.discard': '放弃',

    // Auth
    'auth.appName': '评价同步',
    'auth.appTagline': '管理您的 Google 商家评价',
    'auth.signIn': '登录',
    'auth.signUp': '注册',
    'auth.name': '姓名',
    'auth.namePlaceholder': '您的姓名',
    'auth.email': '邮箱',
    'auth.emailPlaceholder': 'you@example.com',
    'auth.password': '密码',
    'auth.passwordPlaceholder': '至少8个字符',
    'auth.submitSignIn': '登录',
    'auth.submitSignUp': '创建账号',
    'auth.orContinue': '或使用以下方式继续',
    'auth.google': 'Google',

    // App errors
    'app.errorBoundary': '出了点问题。',
    'app.tryAgain': '重试',
    'app.loading': '加载中...',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('app_language') as Language;
    if (savedLang && (savedLang === 'en' || savedLang === 'zh')) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
